"""Generate the world-rework files of the mod from world_data.py.

Run from the repository root:  python3 tools/build_world.py
"""
import collections
import math
import os
import struct
import sys
import textwrap

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from world_data import WORLD, VANILLA, THEMES, FACTIONS  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IDEOLOGIES = ("democratic", "communism", "fascism", "neutrality")
VANILLA_OWNERS = {v["owner"] for v in VANILLA.values()}
POSSIBLE_OVERLORDS = ("ENG", "SOV", "JAP", "USA", "HOL", "FRA", "ITA", "POR", "SPR")
REGIONS = {
    "TUR": "The Two Heirs of Antiquity", "ENG": "The British Isles and the North",
    "FRA": "Western and Central Europe", "SOV": "Rus', the Steppe and the Caucasus",
    "SAU": "Arabia, North and East Africa", "MRT": "West, Central and Southern Africa",
    "AFG": "South Asia", "CHI": "East Asia", "BRM": "Southeast Asia and Oceania", "CAN": "The Americas",
}
GENERIC_PARTIES = {
    "democratic": ("Liberty Assembly", "{adj} Liberty Assembly"),
    "communism": ("Workers' Union", "{adj} Workers' Union"),
    "fascism": ("Iron Banner", "{adj} Iron Banner"),
    "neutrality": ("Crown Loyalists", "{adj} Crown Loyalists"),
}


def path(*p):
    full = os.path.join(ROOT, *p)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    return full


def cos(c):
    return c["code"] if c["custom"] else "AW_" + c["code"]


def ind(s, n=1):
    return textwrap.indent(s, "\t" * n)


def loc_escape(s):
    return s.replace('"', "'").replace("\n", "\\n")


# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------
def validate():
    seen = collections.Counter(s for c in WORLD for s in c["states"])
    errors = []
    errors += [f"state {s} assigned {n} times" for s, n in seen.items() if n > 1]
    errors += [f"state {s} ({VANILLA[s]['name']}) unassigned" for s in VANILLA if s not in seen]
    errors += [f"state {s} does not exist" for s in seen if s not in VANILLA]
    errors += [f"{c['tag']} capital {c['capital']} not in its states" for c in WORLD if c["capital"] not in c["states"]]
    for key in ("tag", "code"):
        dup = [k for k, n in collections.Counter(c[key] for c in WORLD).items() if n > 1]
        errors += [f"duplicate {key} {d}" for d in dup]
    if errors:
        sys.exit("World data invalid:\n  " + "\n  ".join(errors))
    print(f"validated: {len(WORLD)} countries, {len(seen)} states")


# --------------------------------------------------------------------------
# Map + politics setup (scripted effects, called from on_startup)
# --------------------------------------------------------------------------
def popularities(ruling):
    pops = {i: 0 for i in IDEOLOGIES}
    pops[ruling] = 65
    rest = [i for i in IDEOLOGIES if i != ruling]
    for i, share in zip(rest, (15, 12, 8)):
        pops[i] = share
    return " ".join(f"{k} = {v}" for k, v in pops.items())


def gen_effects():
    out = ["# Generated by tools/build_world.py. Do not edit by hand.", ""]

    # --- 1. Map ---
    m = ["aw_redraw_world = {"]
    m.append("\t# End the 1935 war in the Horn of Africa before borders move")
    m.append("\tif = { limit = { ITA = { has_war_with = ETH } } ITA = { white_peace = ETH } }")
    m.append("\tevery_country = { limit = { is_faction_leader = yes } dismantle_faction = yes }")
    m.append("")
    m.append("\t# Bring countries that did not exist in 1936 into being")
    for c in WORLD:
        if c["tag"] in VANILLA_OWNERS:
            continue
        m.append(f"\tif = {{ limit = {{ NOT = {{ country_exists = {c['tag']} }} }} "
                 f"{c['capital']} = {{ add_core_of = {c['tag']} owner = {{ release = {c['tag']} }} }} }}")
    m.append("")
    m.append("\t# Assign every state of the world")
    for c in WORLD:
        ids = sorted(c["states"])
        lines = [" ".join(f"transfer_state = {s}" for s in ids[i:i + 8]) for i in range(0, len(ids), 8)]
        m.append(f"\t{c['tag']} = {{ # {c['name']}")
        m += ["\t\t" + l for l in lines]
        m.append("\t}")
    m.append("}")
    out += m + [""]

    # --- 2. Subjects, factions and cores ---
    d = ["aw_world_diplomacy = {"]
    d.append("\t# Free every country that is not meant to be a subject")
    for c in WORLD:
        if c["overlord"] or c["tag"] not in VANILLA_OWNERS:
            continue
        for o in POSSIBLE_OVERLORDS:
            if o == c["tag"]:
                continue
            d.append(f"\tif = {{ limit = {{ {c['tag']} = {{ is_subject_of = {o} }} }} "
                     f"{o} = {{ set_autonomy = {{ target = {c['tag']} autonomy_state = autonomy_free }} }} }}")
    d.append("\t# Subjects of this world")
    for c in WORLD:
        if c["overlord"]:
            d.append(f"\tif = {{ limit = {{ country_exists = {c['tag']} NOT = {{ {c['tag']} = {{ is_subject_of = {c['overlord']} }} }} }} "
                     f"{c['overlord']} = {{ puppet = {c['tag']} }} }}")
    d.append("\t# Starting alliances")
    for key, (leader, name) in FACTIONS.items():
        members = [c["tag"] for c in WORLD if c["faction"] == key and c["tag"] != leader]
        d.append(f"\t{leader} = {{")
        d.append(f"\t\tcreate_faction = {name}")
        for t in members:
            d.append(f"\t\tif = {{ limit = {{ country_exists = {t} }} add_to_faction = {t} }}")
        d.append("\t}")
    d.append("\t# Wipe 1936 cores and claims-by-core; each country now holds cores on what it owns")
    d.append("\tevery_state = {")
    d.append("\t\tevery_country = {")
    d.append("\t\t\tlimit = { PREV = { is_core_of = PREV NOT = { is_owned_by = PREV } } }")
    d.append("\t\t\tPREV = { remove_core_of = PREV }")
    d.append("\t\t}")
    d.append("\t}")
    d.append("\tevery_country = { every_owned_state = { add_core_of = PREV } }")
    d.append("}")
    out += d + [""]

    # --- 3. Governments, leaders, spirits, armies ---
    g = ["aw_world_governments = {"]
    for c in WORLD:
        if c["custom"]:
            continue
        t, code = c["tag"], cos(c)
        b = [f"set_cosmetic_tag = {code}",
             f"set_capital = {{ state = {c['capital']} }}",
             "set_politics = { ruling_party = %s last_election = \"1934.1.1\" election_frequency = 48 elections_allowed = %s }"
             % (c["ideo"], "yes" if c["ideo"] == "democratic" else "no"),
             f"set_popularities = {{ {popularities(c['ideo'])} }}"]
        for i in IDEOLOGIES:
            b.append(f"set_party_name = {{ ideology = {i} long_name = {code}_{i}_party_long name = {code}_{i}_party }}")
        b.append("create_country_leader = {\n"
                 f"\tname = \"{c['leader']}\"\n\tdesc = \"{code}_lore\"\n\texpire = \"1965.1.1\"\n"
                 f"\tideology = {c['sub']}\n\ttraits = {{ }}\n}}")
        b.append(f"add_ideas = aw_{c['code']}_spirit")
        if t not in VANILLA_OWNERS:
            n = max(2, min(10, len(c["states"]) // 2 + 1))
            b.append("set_technology = { infantry_weapons = 1 infantry_weapons1 = 1 tech_support = 1 tech_recon = 1 gw_artillery = 1 }")
            b.append("division_template = {\n\tname = \"Levy Infantry\"\n\tregiments = {\n"
                     "\t\tinfantry = { x = 0 y = 0 }\n\t\tinfantry = { x = 0 y = 1 }\n\t\tinfantry = { x = 1 y = 0 }\n"
                     "\t\tinfantry = { x = 1 y = 1 }\n\t\tartillery_brigade = { x = 2 y = 0 }\n\t}\n}")
            for k in range(1, n + 1):
                b.append(f"create_unit = {{ division = \"name = \\\"{c['adj']} Levy {k}\\\" division_template = \\\"Levy Infantry\\\" "
                         f"start_experience_factor = 0.2\" owner = {t} }}")
            b.append(f"add_equipment_to_stockpile = {{ type = infantry_equipment_1 amount = {500 * n} }}")
            b.append(f"add_manpower = {5000 * n}")
        g.append(f"\t{t} = {{ # {c['name']}")
        g.append(ind("\n".join(b), 2))
        g.append("\t}")
    g.append("}")
    out += g
    open(path("common", "scripted_effects", "aw_world_effects.txt"), "w", encoding="utf8").write("\n".join(out) + "\n")

    on = """# Redraws the world at game start. The logic lives in common/scripted_effects/aw_world_effects.txt
on_actions = {
	on_startup = {
		effect = {
			if = {
				limit = { NOT = { has_global_flag = aw_world_setup } }
				set_global_flag = aw_world_setup
				aw_redraw_world = yes
				aw_world_diplomacy = yes
				aw_world_governments = yes
				every_country = {
					limit = { is_ai = no }
					country_event = { id = aw.1 days = 1 }
				}
			}
		}
	}
}
"""
    open(path("common", "on_actions", "aw_world_on_actions.txt"), "w", encoding="utf8").write(on)


# --------------------------------------------------------------------------
# National spirits
# --------------------------------------------------------------------------
def gen_ideas():
    out = ["# Generated by tools/build_world.py", "ideas = {", "\tcountry = {"]
    for c in WORLD:
        if c["custom"]:
            continue
        _, _, theme = c["spirit"]
        pic, mods = THEMES[theme]
        out.append(f"\t\taw_{c['code']}_spirit = {{")
        out.append(f"\t\t\tpicture = {pic}")
        out.append("\t\t\tallowed = { always = no }")
        out.append("\t\t\tremoval_cost = -1")
        out.append("\t\t\tmodifier = {")
        out += [f"\t\t\t\t{k} = {v}" for k, v in mods.items()]
        out.append("\t\t\t}")
        out.append("\t\t}")
    for name, pic, mods in [
        ("aw_reformed_bureaucracy", "generic_political_support", {"political_power_gain": 0.15}),
        ("aw_ancient_glory", "generic_political_support", {"war_support_factor": 0.10, "army_morale_factor": 0.05}),
        ("aw_fortress_nation", "generic_fortify", {"army_core_defence_factor": 0.10, "army_defence_factor": 0.05}),
        ("aw_total_mobilization", "generic_manpower", {"conscription": 0.02, "consumer_goods_factor": 0.05}),
    ]:
        out.append(f"\t\t{name} = {{")
        out.append(f"\t\t\tpicture = {pic}\n\t\t\tallowed = {{ always = no }}\n\t\t\tremoval_cost = -1\n\t\t\tmodifier = {{")
        out += [f"\t\t\t\t{k} = {v}" for k, v in mods.items()]
        out.append("\t\t\t}\n\t\t}")
    out += ["\t}", "}"]
    open(path("common", "ideas", "aw_world_ideas.txt"), "w", encoding="utf8").write("\n".join(out) + "\n")


# --------------------------------------------------------------------------
# Events + decisions
# --------------------------------------------------------------------------
def gen_events():
    e = ["# Generated by tools/build_world.py", "add_namespace = aw", "",
         "country_event = {", "\tid = aw.1", "\ttitle = aw.1.t", "\tdesc = aw.1.d",
         "\tpicture = GFX_report_event_generic_read_write", "\tis_triggered_only = yes",
         "\toption = {", "\t\tname = aw.1.a", "\t\tcountry_event = { id = aw.2 }", "\t}", "}", "",
         "country_event = {", "\tid = aw.2", "\ttitle = aw.2.t"]
    for c in WORLD:
        e.append(f"\tdesc = {{ trigger = {{ tag = {c['tag']} }} text = {cos(c)}_lore }}")
    e.append("\tdesc = { trigger = { NOT = { " + " ".join(f"tag = {c['tag']}" for c in WORLD) + " } } text = aw.2.d_other }")
    e += ["\tpicture = GFX_report_event_generic_rally", "\tis_triggered_only = yes",
          "\toption = { name = aw.2.a }", "}"]
    open(path("events", "aw_world_events.txt"), "w", encoding="utf8").write("\n".join(e) + "\n")

    cat = "aw_chronicles = {\n\ticon = generic_political_actions\n\tallowed = { always = yes }\n}\n"
    open(path("common", "decisions", "categories", "aw_categories.txt"), "w", encoding="utf8").write(cat)
    dec = """aw_chronicles = {
	aw_read_the_chronicle = {
		icon = generic_research
		cost = 0
		days_re_enable = 7
		complete_effect = { country_event = { id = aw.2 } }
		ai_will_do = { factor = 0 }
	}
	aw_read_the_world_chronicle = {
		icon = generic_research
		cost = 0
		days_re_enable = 7
		complete_effect = { country_event = { id = aw.1 } }
		ai_will_do = { factor = 0 }
	}
}
"""
    open(path("common", "decisions", "aw_decisions.txt"), "w", encoding="utf8").write(dec)


# --------------------------------------------------------------------------
# Shared focus tree for every country except Rome and Eranshahr
# --------------------------------------------------------------------------
def civ(n=2):
    return ("random_owned_controlled_state = {\n\tlimit = { free_building_slots = { building = industrial_complex size > 1 include_locked = yes } }\n"
            f"\tadd_extra_state_shared_building_slots = {n}\n\tadd_building_construction = {{ type = industrial_complex level = {n} instant_build = yes }}\n}}")


def mil(n=2):
    return ("random_owned_controlled_state = {\n\tlimit = { free_building_slots = { building = arms_factory size > 1 include_locked = yes } }\n"
            f"\tadd_extra_state_shared_building_slots = {n}\n\tadd_building_construction = {{ type = arms_factory level = {n} instant_build = yes }}\n}}")


def set_gov(ideo, elections):
    return (f"add_popularity = {{ ideology = {ideo} popularity = 0.25 }}\n"
            f"if = {{\n\tlimit = {{ NOT = {{ has_government = {ideo} }} }}\n"
            f"\tset_politics = {{ ruling_party = {ideo} elections_allowed = {elections} }}\n}}")


FOCUSES = [
    # id, icon, x, y, prereqs, mutex, reward, filters
    ("aw_convene_the_realm", "GFX_goal_generic_political_pressure", 3, 0, [], [],
     "add_political_power = 100\nadd_stability = 0.05", "FOCUS_FILTER_POLITICAL"),
    ("aw_national_myth", "GFX_goal_generic_propaganda", 2, 1, [["aw_convene_the_realm"]], [],
     "add_war_support = 0.05\nadd_stability = 0.05", "FOCUS_FILTER_STABILITY"),
    ("aw_reform_the_bureaucracy", "GFX_goal_generic_national_unity", 4, 1, [["aw_convene_the_realm"]], [],
     "add_ideas = aw_reformed_bureaucracy", "FOCUS_FILTER_POLITICAL"),
    ("aw_path_of_the_assembly", "GFX_goal_generic_political_pressure", 0, 2, [["aw_national_myth"]],
     ["aw_path_of_the_vanguard", "aw_path_of_the_throne", "aw_path_of_the_iron_banner"], set_gov("democratic", "yes"), "FOCUS_FILTER_POLITICAL"),
    ("aw_path_of_the_vanguard", "GFX_goal_support_communism", 2, 2, [["aw_national_myth"]],
     ["aw_path_of_the_assembly", "aw_path_of_the_throne", "aw_path_of_the_iron_banner"], set_gov("communism", "no"), "FOCUS_FILTER_POLITICAL"),
    ("aw_path_of_the_throne", "GFX_goal_generic_national_unity", 4, 2, [["aw_reform_the_bureaucracy"]],
     ["aw_path_of_the_assembly", "aw_path_of_the_vanguard", "aw_path_of_the_iron_banner"], set_gov("neutrality", "no"), "FOCUS_FILTER_POLITICAL"),
    ("aw_path_of_the_iron_banner", "GFX_goal_support_fascism", 6, 2, [["aw_reform_the_bureaucracy"]],
     ["aw_path_of_the_assembly", "aw_path_of_the_vanguard", "aw_path_of_the_throne"], set_gov("fascism", "no"), "FOCUS_FILTER_POLITICAL"),
    ("aw_ancient_glory", "GFX_goal_generic_major_war", 3, 3,
     [["aw_path_of_the_assembly", "aw_path_of_the_vanguard", "aw_path_of_the_throne", "aw_path_of_the_iron_banner"]], [],
     "add_ideas = aw_ancient_glory", "FOCUS_FILTER_WAR_SUPPORT"),
    ("aw_the_great_game", "GFX_goal_generic_occupy_states_ongoing_war", 3, 4, [["aw_ancient_glory"]], [],
     "add_political_power = 120\narmy_experience = 20\nnavy_experience = 20\nair_experience = 20", "FOCUS_FILTER_POLITICAL"),

    ("aw_industrial_charter", "GFX_goal_generic_production", 9, 0, [], [],
     civ(1) + "\nadd_tech_bonus = { name = aw_industrial_charter bonus = 1 uses = 1 category = industry }", "FOCUS_FILTER_INDUSTRY"),
    ("aw_rail_and_road", "GFX_goal_generic_construct_infrastructure", 8, 1, [["aw_industrial_charter"]], [],
     "every_owned_state = {\n\tlimit = { is_core_of = ROOT }\n\tadd_building_construction = { type = infrastructure level = 1 instant_build = yes }\n}",
     "FOCUS_FILTER_INDUSTRY"),
    ("aw_arsenals", "GFX_goal_generic_construct_mil_factory", 10, 1, [["aw_industrial_charter"]], [], mil(2), "FOCUS_FILTER_INDUSTRY"),
    ("aw_academies", "GFX_goal_generic_scientific_exchange", 8, 2, [["aw_rail_and_road"]], [],
     "add_research_slot = 1", "FOCUS_FILTER_RESEARCH"),
    ("aw_heavy_industry", "GFX_goal_generic_construct_civ_factory", 10, 2, [["aw_arsenals"]], [],
     civ(2) + "\n" + civ(1), "FOCUS_FILTER_INDUSTRY"),
    ("aw_shipyards", "GFX_goal_generic_construct_naval_dockyard", 8, 3, [["aw_academies"]], [],
     "random_owned_controlled_state = {\n\tlimit = { is_coastal = yes free_building_slots = { building = dockyard size > 1 include_locked = yes } }\n"
     "\tadd_extra_state_shared_building_slots = 2\n\tadd_building_construction = { type = dockyard level = 2 instant_build = yes }\n}\n"
     "navy_experience = 15", "FOCUS_FILTER_INDUSTRY"),
    ("aw_war_economy", "GFX_goal_generic_construct_mil_factory", 10, 3, [["aw_heavy_industry"]], [],
     mil(2) + "\n" + mil(1), "FOCUS_FILTER_INDUSTRY"),

    ("aw_army_reform", "GFX_goal_generic_army_doctrines", 14, 0, [], [],
     "army_experience = 20\nadd_tech_bonus = { name = aw_army_reform bonus = 1 uses = 1 category = land_doctrine }", "FOCUS_FILTER_ARMY_XP"),
    ("aw_modern_rifles", "GFX_goal_generic_small_arms", 13, 1, [["aw_army_reform"]], [],
     "add_tech_bonus = { name = aw_modern_rifles bonus = 1 uses = 2 category = infantry_weapons }", "FOCUS_FILTER_RESEARCH"),
    ("aw_iron_cavalry", "GFX_goal_generic_army_tanks", 15, 1, [["aw_army_reform"]], [],
     "add_tech_bonus = { name = aw_iron_cavalry bonus = 1 uses = 2 category = armor }", "FOCUS_FILTER_RESEARCH"),
    ("aw_air_corps", "GFX_goal_generic_build_airforce", 13, 2, [["aw_modern_rifles"]], [],
     "air_experience = 25\nadd_tech_bonus = { name = aw_air_corps bonus = 1 uses = 2 category = air_doctrine }", "FOCUS_FILTER_RESEARCH"),
    ("aw_fortress_nation", "GFX_goal_generic_defence", 15, 2, [["aw_iron_cavalry"]], [],
     "add_ideas = aw_fortress_nation", "FOCUS_FILTER_MANPOWER"),
    ("aw_total_mobilization", "GFX_goal_generic_allies_build_infantry", 14, 3, [["aw_air_corps"], ["aw_fortress_nation"]], [],
     "add_ideas = aw_total_mobilization\nadd_manpower = 25000", "FOCUS_FILTER_MANPOWER"),
]

FOCUS_TEXT = {
    "aw_convene_the_realm": ("Convene the Great Council", "The [ROOT.GetAdjective] realm must gather its leaders and decide its course in a dangerous decade."),
    "aw_national_myth": ("The [ROOT.GetAdjective] Saga", "Every nation of this world has a story. Ours must be taught in every school."),
    "aw_reform_the_bureaucracy": ("Reform the Chancery", "An old state needs a modern administration."),
    "aw_path_of_the_assembly": ("Path of the Assembly", "Power must rest with the people's chosen representatives."),
    "aw_path_of_the_vanguard": ("Path of the Vanguard", "The Roman revolution has shown the way. The workers must rule."),
    "aw_path_of_the_throne": ("Path of the Throne", "Tradition, faith and the crown have carried us for centuries. They will carry us further."),
    "aw_path_of_the_iron_banner": ("Path of the Iron Banner", "Only a nation forged into a single weapon can survive what is coming."),
    "aw_ancient_glory": ("Remember Our Ancient Glory", "Fourteen centuries of history weigh on us, and inspire us."),
    "aw_the_great_game": ("The Great Game", "Rome and Eranshahr are preparing for war. Every other nation must decide where it stands."),
    "aw_industrial_charter": ("Industrial Charter", "Guilds, banks and the state must cooperate to build modern industry."),
    "aw_rail_and_road": ("Rail and Road", "Connect every province to the capital."),
    "aw_arsenals": ("[ROOT.GetAdjective] Arsenals", "Build the factories of war before we need them."),
    "aw_academies": ("Found the Academies", "Our scholars must match those of Constantinople, Nalanda and Hangzhou."),
    "aw_heavy_industry": ("Heavy Industry", "Steel, coal and concrete are the foundations of power."),
    "aw_shipyards": ("Shipyards", "Whoever controls the sea controls the trade of the world."),
    "aw_war_economy": ("War Economy", "Prepare the economy for total war."),
    "aw_army_reform": ("Army Reform", "Our army must be modernized for the age of machines."),
    "aw_modern_rifles": ("Modern Rifles", "Every soldier deserves a reliable rifle."),
    "aw_iron_cavalry": ("Iron Cavalry", "The cataphracts and horse archers of old will return as tanks."),
    "aw_air_corps": ("Air Corps", "The sky is the newest battlefield."),
    "aw_fortress_nation": ("Fortress Nation", "Our homeland will be defended street by street and hill by hill."),
    "aw_total_mobilization": ("Total Mobilization", "Every citizen will serve."),
}


def gen_focus():
    blocks = []
    for fid, icon, x, y, prereq, mutex, reward, filt in FOCUSES:
        b = [f"id = {fid}", f"icon = {icon}", f"x = {x}", f"y = {y}", "cost = 10"]
        for group in prereq:
            b.append("prerequisite = { " + " ".join(f"focus = {p}" for p in group) + " }")
        if mutex:
            b.append("mutually_exclusive = { " + " ".join(f"focus = {p}" for p in mutex) + " }")
        b.append(f"search_filters = {{ {filt} }}")
        b.append("ai_will_do = { factor = 1 }")
        b.append("completion_reward = {\n" + ind(reward) + "\n}")
        blocks.append(ind("focus = {\n" + ind("\n".join(b)) + "\n}"))
    tree = ("# Generated by tools/build_world.py\n"
            "# Shared focus tree for every nation of the reworked world except Rome and Eranshahr,\n"
            "# replacing vanilla trees whose history no longer exists.\n"
            "focus_tree = {\n\tid = aw_world_focus\n\tcountry = {\n\t\tfactor = 0\n"
            "\t\tmodifier = { add = 200 NOT = { tag = TUR tag = PER } }\n\t}\n\tdefault = no\n"
            "\tcontinuous_focus_position = { x = 50 y = 1100 }\n\n" + "\n\n".join(blocks) + "\n}\n")
    open(path("common", "national_focus", "aw_world_focus.txt"), "w", encoding="utf8").write(tree)


# --------------------------------------------------------------------------
# Localisation
# --------------------------------------------------------------------------
WORLD_INTRO = (
    "In this world, the Prophet of Islam was never born.\\n\\n"
    "Rome and Persia, exhausted by the great war of 602-628, made peace and endured. The Arabs remained divided between Roman and Persian clients. "
    "With no Caliphate to cut the Mediterranean in two, Rome kept Egypt, Syria and Africa. Without the Saracen threat there was no Charles Martel, "
    "no Charlemagne and no Holy Roman Empire, so Western Europe stayed a mosaic of Gothic, Frankish, Lombard and Saxon kingdoms. With nothing to crusade against, "
    "no crusades were ever called. The Baltic pagans kept their gods, and the Fourth Crusade never sacked Constantinople.\\n\\n"
    "The Mongols still came. They sacked Kiev and Samarkand, but they were stopped at the walls of Constantinople and Ctesiphon, and their khans turned to Buddhism. "
    "Anglo-Danish longships reached Vinland and stayed. Gothic caravels crossed to the Gulf but met Mexica and Inca empires that learned to fight back. "
    "Gaelic sailors found Hy-Brasil, and Song treasure fleets found Fusang. Across Africa and Asia, empires that Islam's expansion once overthrew or transformed endured: "
    "Aksum, Wagadu, Makuria, the Hindu Shahis, Vijayanagara, Majapahit and Srivijaya.\\n\\n"
    "Then came the Great War of 1912-1918. In 1917 the Constantinople Soviet overthrew the Basileus, and the Roman Proletarian Republic was born. "
    "In 1921 a magus in Persia proclaimed himself the last Saoshyant.\\n\\n"
    "It is 1936. The oldest rivalry in the world has a new ideological edge, and every nation on earth must choose a side."
)


def gen_loc():
    L = ["l_english:", " # Generated by tools/build_world.py"]
    for c in WORLD:
        code = cos(c)
        L.append(f' {code}_lore:0 "{loc_escape(c["lore"])}"')
        if c["custom"]:
            continue
        name, adj = loc_escape(c["name"]), loc_escape(c["adj"])
        defn = name if name.startswith(("Lord ", "Dai Viet", "Tawantinsuyu", "Rapa Nui", "Klein-Venedig", "Great Xia")) else "the " + name
        L.append(f' {code}:0 "{name}"')
        L.append(f' {code}_DEF:0 "{defn}"')
        L.append(f' {code}_ADJ:0 "{adj}"')
        for i in IDEOLOGIES:
            L.append(f' {code}_{i}:0 "{name}"')
            L.append(f' {code}_{i}_DEF:0 "{defn}"')
            L.append(f' {code}_{i}_ADJ:0 "{adj}"')
            if i == c["ideo"] and c["party"]:
                short, long_ = c["party"]
            else:
                short, long_ = GENERIC_PARTIES[i]
                long_ = long_.format(adj=c["adj"])
            L.append(f' {code}_{i}_party:0 "{loc_escape(short)}"')
            L.append(f' {code}_{i}_party_long:0 "{loc_escape(long_)}"')
        sname, sdesc, _ = c["spirit"]
        L.append(f' aw_{c["code"]}_spirit:0 "{loc_escape(sname)}"')
        L.append(f' aw_{c["code"]}_spirit_desc:0 "{loc_escape(sdesc)}"')
    L += [
        ' aw_faction_north_sea_thing:0 "The North Sea Thing"',
        f' aw.1.t:0 "The World That Was Not"',
        f' aw.1.d:0 "{WORLD_INTRO}"',
        ' aw.1.a:0 "And what of us?"',
        ' aw.2.t:0 "The Chronicle of [ROOT.GetNameDef]"',
        ' aw.2.d_other:0 "Our nation has had a turbulent history in this strange world."',
        ' aw.2.a:0 "So it has been. So it shall be."',
        ' aw_chronicles:0 "Chronicles"',
        ' aw_chronicles_desc:0 "Read the history of our nation and of this world."',
        ' aw_read_the_chronicle:0 "Read the Chronicle of Our Nation"',
        ' aw_read_the_world_chronicle:0 "Read the Chronicle of the World"',
        ' aw_reformed_bureaucracy:0 "Reformed Chancery"',
        ' aw_reformed_bureaucracy_desc:0 "A modern civil service, at last."',
        ' aw_ancient_glory:0 "Ancient Glory"',
        ' aw_ancient_glory_desc:0 "Our soldiers march under banners that are a thousand years old."',
        ' aw_fortress_nation:0 "Fortress Nation"',
        ' aw_fortress_nation_desc:0 "Every hill a bastion, every town a citadel."',
        ' aw_total_mobilization:0 "Total Mobilization"',
        ' aw_total_mobilization_desc:0 "The whole nation stands ready."',
    ]
    for fid, (title, desc) in FOCUS_TEXT.items():
        L.append(f' {fid}:0 "{title}"')
        L.append(f' {fid}_desc:0 "{desc}"')
    open(path("localisation", "english", "aw_world_l_english.yml"), "w", encoding="utf-8-sig").write("\n".join(L) + "\n")


# --------------------------------------------------------------------------
# Flags
# --------------------------------------------------------------------------
W, H, SS = 82, 52, 3


def in_poly(px, py, pts):
    inside, j = False, len(pts) - 1
    for i in range(len(pts)):
        xi, yi = pts[i]; xj, yj = pts[j]
        if (yi > py) != (yj > py) and px < (xj - xi) * (py - yi) / (yj - yi) + xi:
            inside = not inside
        j = i
    return inside


def star_pts(cx, cy, r):
    return [(cx + (r if i % 2 == 0 else r * 0.4) * math.cos(-math.pi / 2 + i * math.pi / 5),
             cy + (r if i % 2 == 0 else r * 0.4) * math.sin(-math.pi / 2 + i * math.pi / 5)) for i in range(10)]


def emblem_hit(kind, x, y, cx, cy, s):
    dx, dy = x - cx, y - cy
    d = math.hypot(dx, dy)
    if kind == "star":
        return in_poly(x, y, star_pts(cx, cy, 11 * s))
    if kind == "disc":
        return d < 9 * s
    if kind == "ring":
        return 6.5 * s < d < 10 * s
    if kind == "sun":
        if d < 6 * s:
            return True
        ang = math.atan2(dy, dx)
        return d < 11 * s and math.cos(ang * 12) > 0.55
    if kind == "cross":
        return (abs(dx) < 2.2 * s and abs(dy) < 10 * s) or (abs(dy) < 2.2 * s and abs(dx) < 10 * s)
    if kind == "diamond":
        return abs(dx) / (8 * s) + abs(dy) / (11 * s) < 1
    if kind == "wheel":
        if 7.5 * s < d < 10 * s or d < 2.5 * s:
            return True
        ang = math.atan2(dy, dx)
        return d < 10 * s and abs(math.sin(ang * 4)) < 0.12
    if kind == "flame":
        top, base = cy - 11 * s, cy + 9 * s
        if not (top <= y < base):
            return False
        t = (y - top) / (base - top)
        return abs(dx) < 8 * s * math.sin(t * math.pi * 0.62) ** 1.2
    return False


def flag_pixel(spec, x, y):
    pat, cols, emb, ecol = spec
    c = cols
    col = c[0]
    if pat == "plain":
        col = c[0]
    elif pat == "h2":
        col = c[0] if y < H / 2 else c[1]
    elif pat == "h3":
        col = c[min(2, int(y / (H / 3)))]
    elif pat == "v2":
        col = c[0] if x < W / 2 else c[1]
    elif pat == "v3":
        col = c[min(2, int(x / (W / 3)))]
    elif pat == "stripes":
        col = c[int(y / (H / 7)) % 2]
    elif pat == "nordic":
        cx = W * 0.36
        if abs(x - cx) < 6 or abs(y - H / 2) < 6:
            col = c[1]
            if len(c) > 2 and c[2] and (abs(x - cx) < 2.5 or abs(y - H / 2) < 2.5):
                col = c[2]
    elif pat == "cross":
        if abs(x - W / 2) < 5 or abs(y - H / 2) < 5:
            col = c[1]
    elif pat == "saltire":
        if abs(y - x * H / W) < 4.5 or abs(y - (H - x * H / W)) < 4.5:
            col = c[1]
    elif pat == "canton":
        col = c[1] if (x < W * 0.45 and y < H * 0.5) else c[0]
    elif pat == "tri":
        band = c[1] if y < H / 2 else c[2]
        col = c[0] if x < (H / 2 - abs(y - H / 2)) * 1.2 else band
    elif pat == "quad":
        col = c[0] if ((int(x / 10.25) + int(y / 10.4)) % 2 == 0) else c[1]
    elif pat == "bend":
        col = c[0] if y < H - x * H / W else c[1]

    if emb:
        if pat == "canton":
            cx, cy, s = W * 0.225, H * 0.25, 0.8
        elif pat == "tri":
            cx, cy, s = W * 0.17, H / 2, 0.75
        elif pat == "nordic":
            cx, cy, s = W * 0.16, H * 0.24, 0.6
        else:
            cx, cy, s = W / 2, H / 2, 1.0
        if emb == "canton_cross":
            if x < W * 0.45 and y < H * 0.5:
                col = ecol if (abs(x - W * 0.225) < 2.5 or abs(y - H * 0.25) < 2.5) else WHITE_
        elif emblem_hit(emb, x, y, cx, cy, s):
            col = ecol
        elif sum(abs(a - b) for a, b in zip(col, ecol)) < 160 and any(
                emblem_hit(emb, x + ox, y + oy, cx, cy, s)
                for ox, oy in ((1.6, 0), (-1.6, 0), (0, 1.6), (0, -1.6), (1.1, 1.1), (-1.1, 1.1), (1.1, -1.1), (-1.1, -1.1))):
            # outline the emblem where it would vanish into a same-coloured field
            col = BLACK_ if sum(ecol) > 420 else WHITE_
    return col


WHITE_ = (245, 245, 240)
BLACK_ = (25, 25, 28)


def render_flag(spec, w, h):
    rows = []
    for j in range(h):
        row = []
        for i in range(w):
            acc = [0, 0, 0]
            for sj in range(SS):
                for si in range(SS):
                    c = flag_pixel(spec, (i + (si + .5) / SS) * W / w, (j + (sj + .5) / SS) * H / h)
                    for k in range(3):
                        acc[k] += c[k]
            row.append(tuple(round(a / (SS * SS)) for a in acc))
        rows.append(row)
    return rows


def write_tga(fn, rows):
    h, w = len(rows), len(rows[0])
    data = bytearray(struct.pack("<BBBHHBHHHHBB", 0, 0, 2, 0, 0, 0, 0, 0, w, h, 32, 0x28))
    for row in rows:
        for r, g, b in row:
            data += bytes((b, g, r, 255))
    open(fn, "wb").write(data)


def gen_flags():
    made = []
    for c in WORLD:
        if c["custom"]:
            continue
        code = cos(c)
        for sub, (w, h) in (("", (82, 52)), ("medium", (41, 26)), ("small", (10, 7))):
            img = render_flag(c["flag"], w, h)
            for suffix in ("",) + tuple("_" + i for i in IDEOLOGIES):
                write_tga(path("gfx", "flags", sub, f"{code}{suffix}.tga"), img)
        made.append(code)
    return made


# --------------------------------------------------------------------------
# WORLD.md
# --------------------------------------------------------------------------
IDEO_NAMES = {"democratic": "Democratic", "communism": "Communist", "fascism": "Ultranationalist", "neutrality": "Non-aligned"}


def gen_doc():
    tagname = {c["tag"]: c["name"] for c in WORLD}
    md = ["# The World of *Fire and Hammer*", "",
          "_Generated from `tools/world_data.py`. Every one of the game's 1046 states belongs to one of the "
          f"{len(WORLD)} nations below._", "",
          "## How we got here", "", WORLD_INTRO.replace("\\n\\n", "\n\n"), ""]
    region = None
    for c in WORLD:
        if c["tag"] in REGIONS:
            region = REGIONS[c["tag"]]
            md += [f"## {region}", ""]
        ideo = IDEO_NAMES[c["ideo"]]
        extra = []
        if c["overlord"]:
            extra.append(f"subject of {tagname[c['overlord']]}")
        if c["faction"]:
            extra.append({"red": "Red Ecumene", "fire": "Concord of the Sacred Fire", "north": "North Sea Thing"}[c["faction"]])
        leader = c["leader"] or ("General Secretary Ioannes Komnenos-Markos" if c["tag"] == "TUR" else "Saoshyant Astvat-ereta")
        md.append(f"### {c['name']}")
        md.append(f"*{ideo} · led by {leader} · {len(c['states'])} states · plays as `{c['tag']}`"
                  + (" · " + ", ".join(extra) if extra else "") + "*")
        md.append("")
        md.append(c["lore"])
        if c["spirit"]:
            md.append("")
            md.append(f"**National spirit — {c['spirit'][0]}:** {c['spirit'][1]}")
        md.append("")
    open(path("WORLD.md"), "w", encoding="utf8").write("\n".join(md))


if __name__ == "__main__":
    validate()
    gen_effects()
    gen_ideas()
    gen_events()
    gen_focus()
    gen_loc()
    gen_doc()
    if "--no-flags" not in sys.argv:
        print("flags:", len(gen_flags()))
    print("done")
