"""World data for "Fire and Hammer: The Unbroken East".

Point of divergence: c. 570 AD, Muhammad is never born. There is no Islam,
no Arab conquests, and fourteen centuries of butterflies follow.

Every one of the 1046 vanilla states is assigned to exactly one country below.
`build_world.py` validates that and generates the mod files from this table.
"""
import json
import os

_HERE = os.path.dirname(os.path.abspath(__file__))
VANILLA = {int(k): v for k, v in json.load(open(os.path.join(_HERE, "vanilla_states.json"), encoding="utf8")).items()}


def own(*tags):
    """All 1936 states owned by the given vanilla tags."""
    return [s for s, v in VANILLA.items() if v["owner"] in tags]


def but(lst, *drop):
    return [s for s in lst if s not in drop]


# --------------------------------------------------------------------------
# Flag colours
# --------------------------------------------------------------------------
CRIMSON = (139, 10, 26); RED = (200, 30, 40); SCARLET = (220, 50, 30); MAROON = (100, 20, 30)
GOLD = (232, 184, 48); YELLOW = (250, 210, 40); ORANGE = (235, 120, 25); SAFFRON = (245, 150, 30)
WHITE = (245, 245, 240); CREAM = (240, 230, 205); SILVER = (190, 195, 200); GREY = (110, 115, 120)
BLACK = (25, 25, 28); NAVY = (20, 40, 100); BLUE = (30, 80, 170); SKY = (90, 160, 225)
TEAL = (0, 120, 120); GREEN = (20, 120, 60); LEAF = (70, 160, 60); OLIVE = (100, 110, 40)
PURPLE = (100, 40, 130); VIOLET = (140, 80, 180); BROWN = (110, 70, 35); OCHRE = (190, 130, 50)
TURQ = (40, 180, 170); PINK = (220, 110, 140)

# Spirit themes -> (picture, modifiers)
THEMES = {
    "naval":   ("generic_naval_bonus",        {"industrial_capacity_dockyard": 0.10, "navy_org_factor": 0.05}),
    "trade":   ("generic_production_bonus",   {"consumer_goods_factor": -0.05, "production_speed_buildings_factor": 0.05}),
    "martial": ("generic_army_support",       {"army_attack_factor": 0.05, "experience_gain_army": 0.10}),
    "faith":   ("generic_religious",          {"stability_factor": 0.10, "war_support_factor": 0.05}),
    "steppe":  ("generic_army_support",       {"army_org_factor": 0.05, "army_speed_factor": 0.05}),
    "defense": ("generic_fortify",            {"army_core_defence_factor": 0.10, "stability_factor": 0.05}),
    "scholar": ("generic_research_bonus",     {"research_speed_factor": 0.05}),
    "industry":("generic_production_bonus",   {"industrial_capacity_factory": 0.05, "production_speed_buildings_factor": 0.05}),
    "people":  ("generic_manpower",           {"conscription": 0.01, "stability_factor": 0.03}),
    "unity":   ("generic_political_support",  {"political_power_gain": 0.10, "stability_factor": 0.05}),
    "jungle":  ("generic_fortify",            {"army_core_defence_factor": 0.10, "conscription": 0.005}),
    "revolution": ("generic_communism_drift_bonus", {"political_power_gain": 0.10, "war_support_factor": 0.05}),
}


def C(tag, code, name, adj, ideo, sub, leader, capital, states, spirit, flag, lore,
      party=None, overlord=None, faction=None, custom=False):
    return dict(tag=tag, code=code, name=name, adj=adj, ideo=ideo, sub=sub, leader=leader,
                capital=capital, states=list(states), spirit=spirit, flag=flag, lore=lore,
                party=party, overlord=overlord, faction=faction, custom=custom)


WORLD = [
# ======================================================================
# THE TWO HEIRS OF ANTIQUITY
# ======================================================================
C("TUR", "RPR", "Roman Proletarian Republic", "Roman", "communism", "leninism", None, 797,
  but(own("TUR", "GRE", "SYR", "LEB", "PAL", "JOR"), 800) + [183, 164, 446, 447, 452, 453, 456, 457, 907, 552,
  450, 451, 663, 449, 273, 115, 156, 849, 116, 137],
  None, None,
  "The Rome that never fell. With no Caliphate to tear away Syria, Egypt and Africa, the Empire of the Romans survived the seventh century bruised but whole, outlasted the Mongols behind the Theodosian Walls, and ruled the Mediterranean for another thousand years. In 1917, with the empire starving after the Great War, the Constantinople Soviet stormed the Great Palace and drove the last Basileus into exile. The Roman Proletarian Republic now rules from Sicily to the Nile under the red banner of the Proletarian Synod, and believes Rome was always meant to be universal.",
  faction="red", custom=True),
C("PER", "SAO", "Saoshyantate of Eranshahr", "Eranian", "neutrality", "despotism", None, 266,
  own("PER", "IRQ", "OMA", "KUW") + [1014, 765, 658, 859, 415, 1007, 1009, 584, 832, 444, 445, 988, 1012],
  None, None,
  "The Sasanian realm never fell to Arab armies. It lost wars to Rome and won others, endured the Mongols by converting their khans to the Good Religion, and kept the sacred fires of Zarathustra burning from Ctesiphon to Merv. In 1921 a young magus from Yazd proclaimed himself Astvat-ereta, the last Saoshyant foretold in the Avesta, and the King of Kings knelt before him. The Saoshyantate now prepares for the final battle of Truth against the Lie, and the godless Romans across the Euphrates look very much like the Lie.",
  faction="fire", custom=True),

# ======================================================================
# THE BRITISH ISLES AND THE NORTH
# ======================================================================
C("ENG", "NSE", "North Sea Empire", "Anglo-Danish", "democratic", "conservatism", "Eadric Thorkelsson", 126,
  [122, 123, 125, 126, 127, 128, 129, 130, 131, 132, 338, 931, 932, 933, 909, 100, 696, 703, 704, 710, 713, 720]
  + own("DEN", "NOR"),
  ("Thalassocracy of the Northern Seas", "From London to Trondheim to Greenland, the North Sea is an Anglo-Danish lake.", "naval"),
  ("nordic", [NAVY, CRIMSON, GOLD], "star", GOLD),
  "Cnut the Great's empire of England, Denmark and Norway was meant to die with him. It did not. His sons lived, the Witan and the Things learned to work together, and by 1200 the North Sea Empire was a single maritime state ruled jointly from London and Roskilde. Its longships reached Vinland, Markland and the Cape. Today it is a crowned commonwealth of three peoples with one fleet, governed by the Great Witan and wary of every power that might threaten the sea lanes.",
  party=("Witan", "Party of the Great Witan"), faction="north"),
C("IRE", "GAE", "Gaelic Commonwealth of Éire and Alba", "Gaelic", "democratic", "liberalism", "Aodh Mac Lochlainn", 113,
  [113, 134, 135, 119, 120, 121, 133, 136],
  ("The Brehon Law", "The ancient Gaelic law codes have become a model of constitutional government.", "unity"),
  ("v3", [GREEN, WHITE, GREEN], "ring", GOLD),
  "No Norman ever crossed the Irish Sea. The High Kings of Ireland, allied with the Gaelic kings of Alba through Dál Riata, built a twin realm on the Brehon law and the learning of the monasteries. The Gaels gave the world Hy-Brasil, discovered in 1512 by sailors who set out to find the fabled isle of Saint Brendan's voyage. Today the Commonwealth is a lively parliamentary state that has never forgotten that the Anglo-Danes once burned Armagh.",
  party=("Comhdháil", "Comhdháil na nGael")),
C("SWE", "VAR", "Varangian Kingdom of the Swedes", "Swedish", "neutrality", "oligarchism", "King Erik XXI", 141,
  own("SWE"),
  ("The Varangian Road", "Swedes have served Rome's emperors and Novgorod's merchants for a thousand years.", "martial"),
  ("h3", [SKY, GOLD, SKY], "cross", GOLD),
  "The Swedes went east rather than west. For a thousand years, Varangians from Uppland and Gotland sailed down the Russian rivers to serve as the guard of the Roman emperors. When the Proletarian Republic abolished the guard in 1918, thousands of veterans came home with Roman gold, Roman ideas and Roman grudges. The Varangian Kingdom is now a cautious monarchy of merchant-earls, torn between the Red Ecumene that still recruits its sons and the democratic republic of Novgorod.",
  party=("Rikets Råd", "Council of the Realm")),
C("FIN", "KAL", "Kalevan Realm", "Kalevan", "democratic", "socialism", "Elder Väinö Ilmarinen", 111,
  own("FIN", "EST") + [216],
  ("Sisu of the Forest Peoples", "Finns, Ests and Karelians have never been conquered and do not intend to start now.", "defense"),
  ("nordic", [WHITE, TEAL, None], "sun", GOLD),
  "There were no Northern Crusades, because the crusading idea was never born. The Finnic peoples of Suomi, Karelia and Estland kept their old gods, their sagas and their freedom, and joined into the Kalevan Realm under an elected council of elders. They are named for the land of heroes in their own epic. Today the Realm is a fiercely egalitarian social democracy whose sauna-lodges double as workers' councils.",
  party=("Kalevan Liitto", "Kalevan Union of Labour")),

# ======================================================================
# WESTERN EUROPE
# ======================================================================
C("FRA", "FRK", "Kingdom of the Franks", "Frankish", "democratic", "conservatism", "Mayor of the Palace Childebert Arnulfing", 16,
  [15, 16, 18, 24, 26, 28, 29, 30, 33, 785, 34, 980, 8, 42, 51, 310, 694],
  ("The Long-Haired Kings", "The Merovingian dynasty reigns, while the Mayor of the Palace governs.", "unity"),
  ("v2", [BLUE, GOLD], "disc", RED),
  "Without the Saracen threat there was no Charles Martel and no hammer of Tours. Without Charles Martel there was no Charlemagne. The Merovingian kings kept their long hair and their throne, and their Mayors of the Palace slowly became something like prime ministers. Francia is a sprawling constitutional kingdom from the Loire to the Rhine. It still argues about whether the King should be allowed to cut his hair.",
  party=("Mallus", "Party of the General Mallus")),
C("BRI", "BRE", "Kingdom of Brittany", "Breton", "neutrality", "moderatism", "King Alan XII", 14,
  [14],
  ("Land of the Sea", "Breton fishermen and corsairs are the terror of the Channel.", "naval"),
  ("h2", [BLACK, WHITE], "diamond", BLACK),
  "Brittany was never absorbed by the Franks. Its Celtic kings played Anglo-Danes against Merovingians for a millennium and kept their independence by being too stubborn to conquer. It is a small, proud maritime kingdom of granite, saints and sardine fleets.",
  party=("Breuriezh", "Brotherhood of the Duchy")),
C("OCC", "AQU", "Kingdom of Aquitaine", "Aquitanian", "democratic", "socialism", "Premier Eudes Garsia", 19,
  [19, 31, 22, 806, 25, 23],
  ("Courts of Love", "The troubadour tradition has given Aquitaine a culture of debate and art.", "scholar"),
  ("v3", [RED, YELLOW, RED], "cross", RED),
  "Duke Eudo of Aquitaine never had to beg the Franks for help against an invasion that never came. Aquitaine stayed a separate realm of Gascons, Occitans and Poitevins, home of troubadours and of the strangest heresies of the Middle Ages. It became Europe's first socialist kingdom in 1891, when a general strike in Bordeaux forced the crown to accept the workers' charter.",
  party=("Parlament", "Parlament de l'Occitania")),
C("SWI", "BUR", "Kingdom of Burgundy", "Burgundian", "neutrality", "oligarchism", "King Gundobad IX", 20,
  own("SWI") + [20, 32, 21, 851, 735, 27, 17],
  ("Lords of the Alpine Passes", "Whoever holds the passes holds the trade of Europe.", "defense"),
  ("saltire", [WHITE, RED], "sun", GOLD),
  "The Burgundian kingdom of the Rhône survived both the Franks and the Lombards by holding the Alpine passes and charging everyone a toll. Its kings rule from Lyon over a federation of cantons, prince-bishoprics and banking houses. Burgundy is the richest country in Europe per head and the least interested in anyone else's wars.",
  party=("Diète", "Burgundian Diet")),
C("HOL", "FRI", "Frisian Free Republic", "Frisian", "democratic", "liberalism", "Potestaat Sjoerd Wiarda", 7,
  [7, 35, 36, 309, 695],
  ("Frisian Freedom", "No Frisian has bowed to a lord in a thousand years.", "trade"),
  ("stripes", [BLUE, WHITE], "disc", RED),
  "The Frisians beat the Franks at sea in the eighth century and never stopped trading. Their 'Frisian Freedom' (no lords, no serfs, only free farmers and merchants under elected potestaats) became the oldest republic in Europe. In the 1760s the Frisian engine started the industrial revolution in the polders. The republic still keeps colonies in Guiana and Curaçao.",
  party=("Upstalsboom", "League of the Upstalsboom")),
C("BEL", "FLA", "Free Cities of Flanders", "Flemish", "democratic", "conservatism", "Grand Burgher Jacob van Artevelde", 6,
  [6, 977],
  ("Cloth and Coin", "The looms of Ghent and the docks of Antwerp never sleep.", "trade"),
  ("h2", [YELLOW, BLACK], "star", YELLOW),
  "Bruges, Ghent and Antwerp grew rich on wool and freedom and formed a league of free cities that no king ever managed to swallow. The Free Cities are run by their guilds and burghers from the Cloth Hall of Ghent. They are small, wealthy, heavily fortified and in debt to nobody.",
  party=("Gilden", "Union of the Guilds")),
C("SPR", "GTH", "Gothic Kingdom of Hispania", "Gothic", "fascism", "falangism", "Caudillo Recaredo Ervigio", 41,
  but(own("SPR", "POR"), 172, 792, 290, 783, 297, 296, 540, 544, 796, 891, 892, 896, 897, 721, 729, 321) + [118],
  ("Councils of Toledo", "Church and Crown speak with one voice, and that voice is not gentle.", "faith"),
  ("h3", [CRIMSON, GOLD, CRIMSON], "cross", CRIMSON),
  "In 711 nobody crossed the Strait of Gibraltar. The Visigothic kingdom of Toledo survived its own civil wars and in time united the whole peninsula under the Councils of Toledo. In 1492 Gothic caravels crossed the Atlantic and founded New Gothia on the shores of the Gulf, though they never managed to conquer the great native empires. Since 1931 Hispania has been ruled by a Caudillo who promises to restore the Gothic crown in its old glory.",
  party=("Concilio", "Movement of the Seventeenth Council")),
C("NAV", "NVR", "Kingdom of Navarre", "Navarrese", "neutrality", "moderatism", "Queen Urraca V", 172,
  [172, 792],
  ("The Old Laws", "The fueros of the Basques are older than any kingdom around them.", "defense"),
  ("plain", [RED], "ring", GOLD),
  "The Basques have outlasted Romans, Goths and Franks in their mountains, and the Kingdom of Navarre has kept the passes of Roncesvalles for twelve centuries. It is a small mountain kingdom with ancient laws and an excellent navy of whalers. It would like the Goths to stop looking at it like that.",
  party=("Batzarra", "Assembly of the Fueros")),
C("ITA", "LOM", "Kingdom of the Lombards", "Lombard", "fascism", "fascism_ideology", "Duce Desiderio Agilulfi", 159,
  [2, 39, 114, 117, 157, 158, 159, 160, 161, 162, 850, 736, 852, 1],
  ("The Iron Crown", "The Lombards took Rome from the Romans once. They intend to keep it.", "martial"),
  ("v2", [BLUE, WHITE], "cross", BLUE),
  "No Frankish king came over the Alps to save the Pope in 754. The Lombards took Ravenna, then Rome, and crowned their kings with the Iron Crown in Pavia for the next twelve centuries. The Roman Empire held on in Sicily and the south, and has wanted the Eternal City back ever since. In 1922 the Duce marched on Pavia promising to finish the Lombard conquest of Italy, and he has been preparing the Kingdom for war against the Reds of Constantinople ever since.",
  party=("Corona Ferrea", "Movement of the Iron Crown")),
C("GER", "HAN", "Hanseatic Union", "Hanseatic", "democratic", "liberalism", "Ratsherr-General Heinrich Wullenwever", 58,
  [56, 57, 58, 59, 61, 62, 63, 64, 65, 60, 55, 68, 85, 807],
  ("Diet of the Hanse", "Lübeck law, Lübeck ships and Lübeck credit bind the northern cities together.", "trade"),
  ("h2", [WHITE, RED], "star", RED),
  "No Charlemagne ever butchered the Saxons at Verden. They converted slowly and willingly, and their trading towns grew into a confederation of free cities governed from Lübeck. There is no 'Germany' in this world, only the Hanse. It is a merchant republic of a hundred towns, the banker of the North, and the owner of colonies in Venezuela. It is rich, liberal, quarrelsome and deeply unsure whether it can fight a real war.",
  party=("Hansetag", "Party of the Hansetag"), ),
C("AUS", "BAV", "Agilolfing Kingdom of Bavaria", "Bavarian", "neutrality", "despotism", "Duke Tassilo VII", 53,
  [52, 53, 54, 50, 978, 4, 152, 153, 848, 976],
  ("Stem Duchy", "The Agilolfings have ruled the Bavarii since before there was a France.", "people"),
  ("quad", [SKY, WHITE], None, None),
  "Duke Tassilo III kept his duchy in 788 because there was no Charlemagne to depose him. His descendants united the southern Germans of the Danube and the Alps into a stern Catholic kingdom. Bavaria is the Hanse's poorer, more pious and better-armed southern cousin, and it is ruled by a duke who distrusts merchants, Reds and Avars in that order.",
  party=("Herzogsrat", "Ducal Council")),
C("CZE", "MOR", "Great Moravian Republic", "Moravian", "democratic", "conservatism", "President Svätopluk Mojmírovič", 75,
  [9, 69, 972, 74, 75, 70, 71, 73, 72, 66, 67, 88, 762],
  ("Heirs of Cyril and Methodius", "Great Moravia's Slavonic liturgy made it the cultural heart of the Slavs.", "scholar"),
  ("h3", [WHITE, RED, BLUE], "cross", WHITE),
  "Great Moravia should have fallen to the Magyars in 907. Here the Magyars were swallowed by the Avars, the Avars were exhausted by Moravia, and the Slavic empire of Svatopluk endured. Its Slavonic liturgy and Glagolitic script spread across the Slavic world. Today it is a prosperous industrial republic from Bohemia to Kraków, and it guards its southern border against the Khagan.",
  party=("Sněm", "Great Moravian Assembly")),
C("HUN", "AVR", "Avar Khaganate", "Avar", "fascism", "fascism_ideology", "Khagan Bayan VI", 43,
  [43, 154, 155, 973, 974, 975, 664, 45, 764, 82, 83, 84, 76],
  ("The Ring of the Khagan", "The great ring-fortresses of the Avars have been rebuilt in concrete.", "steppe"),
  ("tri", [BLACK, GOLD, RED], "sun", GOLD),
  "In this world no Charlemagne destroyed the Avar Ring in 796. The Avar Khaganate held the Pannonian plain, absorbed the Magyar tribes when they arrived, and settled into a steppe aristocracy ruling over Slavs, Vlachs and Germans. The khagans converted to Christianity late and halfheartedly. In 1933 Khagan Bayan VI took power in a putsch, and he now preaches a cult of the steppe, of race and of conquest. Moravia, Dacia and Bavaria are frightened, and they are right to be.",
  party=("Tudun", "Movement of the Ring")),
C("SLV", "CAR", "Principality of Carantania", "Carantanian", "neutrality", "moderatism", "Knez Valuk IV", 853,
  [102, 853],
  ("The Prince's Stone", "Carantanian princes are installed by peasants at the ancient Prince's Stone.", "unity"),
  ("h3", [WHITE, BLUE, RED], "star", GOLD),
  "The Slavic principality of Carantania still installs its princes the way it did in 650: a peasant sits on the Prince's Stone and asks the new ruler whether he will be just. Then the prince answers, the peasant gets up and the crowd cheers. It is a small Alpine state that its neighbours protect mostly so that none of them gets it.",
  party=("Knežji Kamen", "Party of the Prince's Stone")),
C("CRO", "CRT", "Kingdom of Croatia and Dalmatia", "Croatian", "neutrality", "oligarchism", "King Tomislav V", 109,
  [109, 103, 104, 804, 163],
  ("Dalmatian Fleet", "The ports of the Adriatic coast give Croatia a fine navy.", "naval"),
  ("h3", [RED, WHITE, BLUE], "diamond", RED),
  "Croatia was founded by Tomislav in 925 and was never folded into Hungary, because there was no Hungary to fold it into. It holds the Dalmatian coast against Lombard, Roman and Avar ambitions alike. It is a Catholic-Orthodox kingdom with a Glagolitic church, a merchant aristocracy and a very anxious foreign ministry.",
  party=("Sabor", "Party of the Sabor")),
C("SER", "SRB", "Grand Župania of Serbia", "Serbian", "neutrality", "despotism", "Grand Župan Vlastimir III", 107,
  [107, 108, 105, 802, 803],
  ("Mountain Militia", "Every Serbian household keeps a rifle, by law and by habit.", "people"),
  ("h3", [RED, BLUE, WHITE], "cross", GOLD),
  "The Serbs never met the Ottomans, because there were no Ottomans. Their Grand Župania grew as a Roman client, a Roman rival and a Roman client again. It is a hard mountain realm ruled by a stern grand župan, and it is deeply alarmed that its old patron in Constantinople has started preaching revolution.",
  party=("Sabor", "Grand Council of Župans")),
C("ALB", "ARB", "Principality of Arbanon", "Arbanian", "neutrality", "despotism", "Archon Progon Skurra", 44,
  [44, 934, 805],
  ("Highland Clans", "Arbanon is a confederation of clans who agree on very little except independence.", "defense"),
  ("plain", [CRIMSON], "star", BLACK),
  "The Principality of Arbanon was founded by the archon Progon in 1190 and has survived ever since by being difficult to reach and impossible to rule. Its clans answer to the archon only in time of war, and they have not decided yet whether this is a time of war.",
  party=("Besa", "Party of the Sworn Word")),
C("BUL", "BLG", "Tsardom of the Bulgars", "Bulgar", "fascism", "fascism_ideology", "Tsar Krum IV", 48,
  [48, 211, 212, 801, 106, 970, 77],
  ("Khan's Inheritance", "The Bulgars remember that their khans once besieged Constantinople.", "martial"),
  ("h3", [WHITE, GREEN, RED], "ring", GOLD),
  "Basil the Bulgar-Slayer died young in this world and the First Bulgarian Empire never fell. For a thousand years the Tsars of Preslav and Constantinople fought, married and betrayed each other. Since the Roman revolution the Bulgar tsardom has become the shield of every monarchy in the Balkans against the Red Ecumene. Tsar Krum IV dreams of finishing what his namesake started in 813.",
  party=("Sabor", "Tsar's Legion")),
C("ROM", "DAC", "Dacian Soviet Republic", "Dacian", "communism", "marxism", "Chairman Decebal Ionescu", 46,
  [46, 81, 79, 80, 78, 766, 971],
  ("Children of Trajan", "The Dacians say they are the westernmost Romans, and the Red Ecumene agrees.", "revolution"),
  ("v3", [BLUE, YELLOW, RED], "star", YELLOW),
  "The Vlachs north of the Danube always called themselves Romans. In 1918 they took the Roman revolution as their own, and the Dacian Soviet Republic was proclaimed in Bucharest under the protection of the Red Ecumene. It is Rome's most loyal ally in Europe, and the Avar Khagan's first target.",
  party=("Sovietul", "Dacian Workers' Soviet"), overlord="TUR", faction="red"),
C("LIT", "RMV", "Grand Duchy of Romuva", "Romuvan", "neutrality", "moderatism", "Krivis Algirdas Vaidotas", 784,
  [11, 188, 189, 814, 815, 12, 190, 808, 809, 810, 763, 5, 784, 96, 95, 94, 206, 207],
  ("Sacred Groves", "The oak groves of Perkūnas are protected by law and by soldiers.", "faith"),
  ("h3", [YELLOW, GREEN, RED], "sun", YELLOW),
  "Without crusades there were no Teutonic Knights. The Baltic peoples (Prussians, Lithuanians, Latvians and Curonians) kept their gods, and in the fourteenth century the Grand Dukes of Lithuania united them into Romuva, named for the great temple of the old faith. Romuva is Europe's last great pagan state, a land of sacred groves, eternal fires and a surprisingly efficient railway. It is ruled jointly by a Grand Duke and the Krivis, the high priest.",
  party=("Romuva", "Council of the Eternal Flame")),
C("POL", "PLN", "Kingdom of the Polans", "Polan", "neutrality", "oligarchism", "King Bolesław XIV", 86,
  [10, 86, 87, 90, 92, 97, 98],
  ("Piast Crown", "The Piast dynasty has ruled Poland without interruption since Mieszko I.", "people"),
  ("h2", [WHITE, RED], "star", WHITE),
  "The Piast kings of Gniezno never split their realm and never lost it. The Kingdom of the Polans is a conservative noble republic in all but name, wedged between Moravians, Romuvans, Hanseatics and Rus. It is ruled by a Sejm of magnates and a king who mostly attends ceremonies.",
  party=("Sejm", "Party of the Szlachta")),

# ======================================================================
# RUS, THE STEPPE AND THE CAUCASUS
# ======================================================================
C("SOV", "NOV", "Lord Novgorod the Great", "Novgorodian", "democratic", "liberalism", "Posadnik Marfa Boretskaya-Volkova", 263,
  [195, 263, 209, 208, 244, 264, 213, 214, 215, 351, 879, 880, 262, 397, 825, 247, 248, 246, 210, 400, 398,
   653, 572, 573, 581, 403, 580, 571, 570, 578, 577, 579, 824, 516, 878, 568, 576, 569, 40, 654, 566, 567, 575,
   565, 574, 876, 877, 644, 874, 562, 637, 822, 875, 463, 650],
  ("The Veche Bell", "When the bell of Saint Sophia rings, all free Novgorodians have a voice.", "trade"),
  ("v2", [WHITE, BLUE], "cross", GOLD),
  "Moscow never rose to crush Novgorod, because the Mongol storm that made Moscow broke against Kiev instead. The merchant republic of Lord Novgorod the Great kept its veche assembly and its bell, and sent its river-pirates and fur-traders east across the Urals, through Siberia and over the strait to Alaska. Novgorod is the largest democracy on earth. Its people are proud, quarrelsome and extremely cold.",
  party=("Veche", "Party of the Veche")),
C("UKR", "KRS", "Tsardom of Kievan Rus'", "Rus'", "neutrality", "despotism", "Grand Prince Yaroslav XII", 202,
  [192, 193, 196, 197, 198, 199, 200, 201, 202, 203, 225, 226, 227, 228, 259, 221, 834,
   219, 220, 222, 223, 224, 205, 254, 257, 258, 260, 240, 253, 252, 204, 241, 194, 242, 243, 91, 89, 93],
  ("Mother of Rus' Cities", "Kiev was rebuilt in gold after the Mongols and has never been taken since.", "people"),
  ("h2", [GOLD, BLUE], "cross", GOLD),
  "The Mongols sacked Kiev in 1240 as they did in our world, but here the Rus' princes rallied around it instead of scattering. After two centuries of tribute, Grand Prince Daniel's heirs threw off the Horde and rebuilt the Golden Gate. The Tsardom of Kievan Rus' is a vast, devout and autocratic Orthodox state. It sees Novgorod as a rebellious province, Romuva as heathen and the Roman Republic as an apostate.",
  party=("Duma", "Boyar Duma")),
C("TAT", "VBG", "Volga Bulgar Khanate", "Volga Bulgar", "neutrality", "despotism", "Elteber Almış VIII", 249,
  [249, 250, 251, 256, 833, 399, 255, 651, 652, 582],
  ("Tengri's Mandate", "The Volga Bulgars keep the faith of the Blue Sky and the trade of the great river.", "steppe"),
  ("h2", [SKY, GREEN], "sun", GOLD),
  "In 922 no envoy came from Baghdad to convert the Volga Bulgars, because there was no Baghdad and nothing to convert them to. The khans of Bolghar stayed true to Tengri, the Eternal Blue Sky. They survived the Mongols by joining them and grew rich on the Volga trade between Novgorod, the Khazars and Persia. Today the Khanate is a Tengrist steppe monarchy of trading cities and horse herds.",
  party=("Kurultai", "Great Kurultai")),
C("KAZ", "KHZ", "Khazar Khaganate", "Khazar", "neutrality", "oligarchism", "Bek Obadiah ben Joseph", 236,
  [236, 237, 217, 238, 218, 245, 234, 235, 232, 821, 827, 828, 406, 407, 402, 401, 239, 829, 265, 590, 881, 882, 588, 583, 587, 404, 589],
  ("The Khaganate of the Covenant", "The Khazar elite's Judaism binds a multi-faith steppe empire together.", "unity"),
  ("h3", [SKY, WHITE, SKY], "star", GOLD),
  "In our world the Khazars were ground down between the Caliphate and the Rus'. Here the Caliphate never existed, and the Jewish Khaganate of Itil held the steppe from the Don to the Irtysh. The Khazar Khagan is a sacred figure who appears once a year. The real ruler is the Bek, who governs a tolerant empire of Jews, Christians, Tengrists and Buddhists from the Volga delta. The Khaganate controls the Caspian oil fields of Baku's northern cousin, Grozny, and everyone wants them.",
  party=("Sanhedrin", "Council of the Bek")),
C("GEO", "IBR", "Kingdom of Iberia-Lazica", "Georgian", "neutrality", "oligarchism", "King Vakhtang IX", 231,
  [231, 826, 233],
  ("Golden Age Never Ended", "Georgia's medieval golden age simply never stopped.", "scholar"),
  ("cross", [WHITE, RED], "cross", RED),
  "Queen Tamar's golden age was never cut short by Mongol and Timurid catastrophes. The Bagrationi kings of Georgia still rule Iberia and Lazica from Tbilisi as a cultured Orthodox kingdom. Their fortresses guard the passes of the Caucasus, and they cannot decide whether to fear Rome or the Khazars more.",
  party=("Darbazi", "Royal Darbazi")),
C("ARM", "HAY", "Kingdom of Greater Armenia", "Armenian", "neutrality", "moderatism", "King Tigranes XIV", 230,
  [230, 800],
  ("First Christian Kingdom", "Armenia was the first kingdom to adopt Christianity, and it never let anyone forget it.", "faith"),
  ("h3", [RED, BLUE, ORANGE], "cross", GOLD),
  "Armenia spent two thousand years as the battlefield between Rome and Persia, and it learned to survive by being too useful to destroy. The Bagratid kings of Ani rule a small, ancient, mountain kingdom from the shores of Lake Van. Every Roman-Persian war starts by marching through it.",
  party=("Azgayin Zhoghov", "National Assembly")),
C("AZR", "ALN", "Kingdom of Caucasian Albania", "Albanian", "neutrality", "despotism", "King Vachagan IV", 229,
  [229],
  ("Land of Eternal Fire", "Natural gas fires have burned at the temples of Baku since antiquity.", "industry"),
  ("h3", [BLUE, RED, GREEN], "flame", ORANGE),
  "The Christian kingdom of Caucasian Albania (Aghvank to its people) was never Islamized and never absorbed by its neighbours. It sits on the oil of Baku, which makes it very rich, very small and very nervous.",
  party=("Divan", "Royal Divan")),
C("UZB", "SOG", "Sogdian Republic", "Sogdian", "democratic", "liberalism", "Ikhshid-Elect Dewashtich Sogdiani", 830,
  [405, 585, 830, 831, 823, 742, 732],
  ("Merchants of the Silk Road", "Sogdian traders still carry silk, paper and ideas between China and Rome.", "trade"),
  ("v3", [TURQ, WHITE, TURQ], "star", GOLD),
  "The Sogdians were the great merchants of the Silk Road, and here no Arab general ever burned Samarkand. Their city-states of Samarkand, Bukhara and Khwarazm formed a merchant republic that survived the Mongols by financing them. Zoroastrian, Buddhist, Manichaean and Christian traders all sit in its elected council. It is the crossroads of Asia, and it knows that crossroads tend to get trampled.",
  party=("Sughd", "Council of the Caravan Cities")),

# ======================================================================
# ARABIA, NORTH AND EAST AFRICA
# ======================================================================
C("SAU", "GHS", "Ghassanid Kingdom", "Ghassanid", "neutrality", "oligarchism", "Phylarch al-Harith XI", 679,
  [854, 855, 679, 856, 857],
  ("Roman Phylarchs", "The Ghassanids have been Rome's Arab allies since the days of Justinian.", "steppe"),
  ("v2", [CRIMSON, WHITE], "cross", GOLD),
  "Without Islam the Arabs never united. The Christian Ghassanid kings stayed what they were in 570: phylarchs of Rome guarding the desert frontier of the Hejaz. When Rome turned red, the Ghassanids became the strangest client of the Proletarian Republic, a Christian Arab monarchy protected by atheist Marxists and quite happy with the arrangement.",
  party=("Majlis", "Council of Phylarchs"), overlord="TUR"),
C("QAT", "LKH", "Lakhmid Kingdom", "Lakhmid", "neutrality", "despotism", "King al-Mundhir IX", 292,
  [292, 678],
  ("Persian Shield", "The Lakhmids guard the desert flank of Eranshahr in return for gold and fire.", "steppe"),
  ("h2", [WHITE, GREEN], "flame", GOLD),
  "The Lakhmid kings of al-Hira were Persia's Arab clients in 570, and in this world they still are. Pushed out of Mesopotamia into the Nejd, they rule the heart of Arabia as vassals of the Saoshyant. Their proxy wars with the Roman-backed Ghassanids across the sands are as old as the empires themselves.",
  party=("Majlis", "Royal Majlis"), overlord="PER", faction="fire"),
C("ETH", "AKS", "Aksumite Empire", "Aksumite", "neutrality", "despotism", "Negusa Nagast Ezana XII", 842,
  own("ETH") + [550, 908, 268, 269, 559, 293, 659, 992, 858, 906],
  ("Ships of the Erythraean Sea", "Aksum controls both shores of the Red Sea and the trade that flows through it.", "naval"),
  ("h3", [GREEN, YELLOW, RED], "star", BLUE),
  "Aksum declined in our world partly because Islam redirected the trade of the Red Sea. Here it never did. The Kings of Kings of Aksum still rule both shores of the Red Sea, from the Ethiopian highlands to Himyar in Yemen. They hold the gateway to the Indian Ocean, and the Lombards tried in 1935 to take it from them. That war ended in humiliation for Pavia.",
  party=("Mesfint", "Council of Princes")),
C("SUD", "MAK", "Kingdom of Makuria", "Makurian", "neutrality", "oligarchism", "King Merkurios IV", 551,
  [551, 549, 767, 887, 883, 886, 884, 885],
  ("Archers of Nubia", "The 'pupil-smiters' of Nubia are still the finest marksmen in Africa.", "martial"),
  ("v3", [ORANGE, WHITE, ORANGE], "cross", BLUE),
  "The Christian kingdoms of Nubia were slowly strangled by the Mamluks in our world. Here they united under Makuria and flourished on the Nile trade between Rome's Egypt and Aksum. Makuria is an old, Coptic-speaking monarchy with Nubian archers, Greek bishops and a long memory of Roman condescension.",
  party=("Eparchy", "Council of the Eparchs")),
C("TUN", "EXA", "Exarchate of Africa", "African", "democratic", "conservatism", "Exarch Gregorius Massinissa", 458,
  [458, 665, 459, 460, 513, 514, 461, 462, 783, 290, 448, 661, 662],
  ("Latin Africa", "Africa remains a Latin-speaking land of Augustine, olives and grain.", "unity"),
  ("v2", [WHITE, BLUE], "cross", GOLD),
  "Roman Africa was never conquered. The Exarchs of Carthage broke away from Constantinople in the eleventh century and built a Latin-Berber state from Tripoli to the Atlantic, the land of Saint Augustine. It is Catholic, Latin-speaking and parliamentary. When Rome went red in 1917 the Exarchate's own revolutionaries were crushed, and Carthage now regards Constantinople with fear and suspicion.",
  party=("Senatus", "Senate of Carthage")),

# ======================================================================
# WEST AND CENTRAL AFRICA
# ======================================================================
C("MRT", "WAG", "Empire of Wagadu", "Soninke", "neutrality", "despotism", "Kaya Maghan Dinga Cissé", 557,
  [557, 786, 899, 556],
  ("Land of Gold", "Wagadu has controlled the gold of the Sahel for fifteen hundred years.", "trade"),
  ("h3", [GOLD, GREEN, GOLD], "disc", RED),
  "The Ghana Empire fell to the Almoravids in 1076, and the Almoravids were a movement of Islamic reform. Without them, Wagadu endured. The Kaya Maghan, the 'Lord of Gold', still rules the oldest empire of West Africa from Koumbi Saleh, and still keeps the snake-spirit Bida happy with the annual offering.",
  party=("Kafu", "Council of Kafus")),
C("MLI", "SNG", "Songhai Kingdom", "Songhai", "neutrality", "despotism", "Dia Kossoi XX", 898,
  [782, 898],
  ("Masters of the Niger", "Songhai river-fleets control the great bend of the Niger.", "naval"),
  ("h2", [GREEN, ORANGE], "ring", WHITE),
  "The Dia dynasty of Gao converted to nothing in particular and ruled the Niger bend through river-boats and sorcerer-priests. Timbuktu became a city of libraries all the same: philosophers from Carthage, Aksum and Wagadu study there.",
  party=("Sohanci", "Council of the Sohanci")),
C("NGR", "TUA", "Kel Tamasheq Confederation", "Tuareg", "neutrality", "moderatism", "Amenokal Dassine ult Ihemma", 515,
  [515, 781],
  ("Lords of the Sahara", "Nobody crosses the desert without the Tuareg's permission.", "steppe"),
  ("h3", [BLUE, WHITE, BLUE], "diamond", BLUE),
  "The Tuareg kept their own faith and their matrilineal traditions, and their drum-groups formed a great confederation across the central Sahara. The Amenokal is elected by the tribal mothers. Caravan routes from Carthage to the Niger all pay her toll.",
  party=("Tobol", "Assembly of the Drum-Groups")),
C("CHA", "KNM", "Kanem Empire", "Kanembu", "neutrality", "despotism", "Mai Dunama XII", 774,
  [774, 775, 901],
  ("Cavalry of the Lake", "Kanem's armoured horsemen still dominate the plains around Lake Chad.", "steppe"),
  ("v3", [BLUE, YELLOW, RED], "ring", WHITE),
  "The Sayfawa kings of Kanem ruled around Lake Chad for a thousand years without converting, holding the trade routes between the Mediterranean and the forest. The Mai is still a sacred king who speaks to his subjects from behind a screen.",
  party=("Majlis", "Council of Twelve")),
C("SOK", "HAU", "Hausa Bakwai Confederation", "Hausa", "neutrality", "oligarchism", "Sarkin Kano Bagauda XIX", 902,
  [902, 900],
  ("City of Dyers", "Kano's indigo pits and markets are the busiest in Africa.", "industry"),
  ("h2", [GREEN, WHITE], "star", GREEN),
  "No jihad swept the Hausa states in 1804, so the seven cities of Hausaland (Kano, Katsina, Zaria and the rest) remained a league of walled trading republics under their sarkis. The confederation is now one of Africa's industrial powers.",
  party=("Bakwai", "Council of the Seven Cities")),
C("NGA", "OYO", "Oyo Empire", "Yoruba", "neutrality", "oligarchism", "Alaafin Atiba II", 558,
  [558, 776, 777],
  ("Oyo Mesi", "The Alaafin rules, but the Oyo Mesi council can command him to open the calabash.", "people"),
  ("h3", [GREEN, WHITE, GREEN], "disc", RED),
  "The Yoruba empire of Oyo never collapsed under the Fulani jihad, because there was none. Its cavalry, its council of nobles and its sacred king rule from the savannah to the sea at Lagos, where Gothic and Frisian merchants trade for palm oil.",
  party=("Oyo Mesi", "Council of the Oyo Mesi")),
C("GHA", "ASH", "Ashanti Empire", "Ashanti", "neutrality", "despotism", "Asantehene Osei Tutu IV", 274,
  [274, 779],
  ("The Golden Stool", "The Golden Stool holds the soul of the Ashanti nation.", "faith"),
  ("h3", [YELLOW, BLACK, GREEN], "star", BLACK),
  "The Ashanti were never conquered by Anglo-Danish or Frisian guns. The Golden Stool still sits in Kumasi, and the Asantehene rules the gold coast with a professional army and a sophisticated bureaucracy.",
  party=("Asantemanhyiamu", "Ashanti Confederacy Council")),
C("VOL", "MOS", "Mossi Kingdoms", "Mossi", "neutrality", "despotism", "Mogho Naba Kom III", 778,
  [778],
  ("Riders of Ouagadougou", "Mossi cavalry have defended their kingdoms for six centuries.", "defense"),
  ("h2", [RED, GREEN], "star", YELLOW),
  "The Mossi kingdoms of the Volta resisted every empire around them in our history and do so here too, under the Mogho Naba, the 'King of the World'.",
  party=("Nakomse", "Council of the Nakomse")),
C("SEN", "JOL", "Jolof Empire", "Wolof", "neutrality", "oligarchism", "Buurba Ndiadiane Ndiaye VI", 272,
  [272, 701, 296],
  ("Griots of Jolof", "The griots keep the memory and the morale of the Wolof nation.", "unity"),
  ("v3", [GREEN, YELLOW, RED], "star", GREEN),
  "The Wolof empire of Jolof survived the breakup that ended it in our world and became the gateway between Gothic Atlantic shipping and the Sahel.",
  party=("Lingeer", "Royal Council")),
C("GNA", "MNE", "Mane Confederation", "Mane", "neutrality", "moderatism", "Mansa Farma Tamba", 780,
  [780, 700],
  ("Forest Warriors", "The Mane learned to fight in the forests and the mountains of the Futa.", "jungle"),
  ("h3", [RED, YELLOW, GREEN], None, None),
  "The Mande kingdoms of the Futa Jallon and the Sierra form a loose confederation under an elected Mansa. They are poor in factories and rich in iron, rice and stubbornness.",
  party=("Mansaya", "Assembly of the Mansaya")),
C("LIB", "KRU", "Kru Coast Republic", "Kru", "democratic", "socialism", "President Nimba Toe", 298,
  [298],
  ("Krumen", "The Kru are the finest sailors of the West African coast.", "naval"),
  ("stripes", [RED, WHITE], "star", WHITE),
  "The Kru seafarers of the pepper coast built a republic of fishing towns and ship-crews, and Kru sailors now crew merchant ships of every flag on earth.",
  party=("Kru League", "League of the Kru Towns")),
C("CMR", "BAM", "Kingdom of Bamum", "Bamum", "neutrality", "moderatism", "Mfon Njoya II", 773,
  [773, 297, 539],
  ("The Njoya Script", "Bamum's own alphabet gave it the most literate population in Central Africa.", "scholar"),
  ("v3", [GREEN, RED, YELLOW], "star", YELLOW),
  "King Njoya of Bamum invented his own script around 1900 in our world. Here he did so in 1810 and, unhindered by colonial conquest, built a highland kingdom of schools, printing presses and royal engineers that now rules Cameroon and the Gabonese coast.",
  party=("Nji", "Council of the Mfon")),
C("CAR", "AZA", "Azande Kingdoms", "Azande", "neutrality", "despotism", "King Gbudwe II", 660,
  [660],
  ("Avungara Clans", "The ruling Avungara clan leads warriors who know every trail of the forest.", "jungle"),
  ("h2", [BLUE, GREEN], "star", YELLOW),
  "The Azande kingdoms of the Ubangi forests were never broken by slave-raiders from the north. They are ruled by princes of the Avungara line who defend their lands in a forest war that no army has ever won.",
  party=("Avungara", "Avungara Council")),
C("COG", "KON", "Kingdom of Kongo", "Kongo", "neutrality", "oligarchism", "Manikongo Afonso XII", 295,
  [295, 796, 540, 892, 772],
  ("Mbanza Kongo", "Kongo's Christian kings have ruled the Congo river mouth for six centuries.", "faith"),
  ("tri", [RED, YELLOW, RED], "cross", WHITE),
  "The Manikongo converted to Christianity when Gothic missionaries arrived in 1483 and, unlike in our world, the slave trade never gutted the kingdom. Kongo is a great Christian African monarchy that rules both banks of the river from Mbanza Kongo to Luanda.",
  party=("Mwisikongo", "Council of the Mwisikongo")),
C("KAT", "LUN", "Luba-Lunda Commonwealth", "Lunda", "neutrality", "oligarchism", "Mwata Yamvo Mushid IV", 888,
  [888, 889, 890, 718, 538],
  ("Copper of the Heartland", "Lunda copper and Luba iron feed the factories of three continents.", "industry"),
  ("h3", [RED, GREEN, RED], "disc", YELLOW),
  "No Belgian king ever claimed the Congo as his private estate. The Luba and Lunda empires of the African heartland formed a commonwealth under the Mwata Yamvo, the 'Lord of the Viper', and now sell copper and cobalt to every industrial nation on earth.",
  party=("Kanampumba", "Council of Titleholders")),
C("RWA", "RWD", "Kingdom of Rwanda-Burundi", "Rwandan", "neutrality", "despotism", "Mwami Ruganzu IV", 768,
  [768, 769],
  ("Land of a Thousand Hills", "The mountain kingdoms are crowded and very hard to invade.", "defense"),
  ("v2", [SKY, GREEN], "sun", YELLOW),
  "The twin highland kingdoms of Rwanda and Burundi united under one Mwami in 1890. They are crowded, ancient and fiercely independent.",
  party=("Abiru", "Council of the Abiru")),
C("UGA", "BUG", "Kingdom of Buganda", "Ganda", "neutrality", "oligarchism", "Kabaka Kintu XI", 548,
  [548],
  ("The Lukiiko", "Buganda's parliament is the oldest legislature in East Africa.", "unity"),
  ("h3", [BLUE, WHITE, BLUE], "ring", GOLD),
  "Buganda grew into the dominant power of the Great Lakes, with a fleet of war canoes on Lake Nalubaale and a parliament, the Lukiiko, that is older than the North Sea Empire's.",
  party=("Lukiiko", "Party of the Lukiiko")),
C("TZN", "KIL", "Kilwa Thalassocracy", "Swahili", "neutrality", "oligarchism", "Mfalme Bahram Shirazi", 546,
  [546, 547, 903, 904, 905, 844],
  ("Monsoon Trade", "Kilwa's dhows sail with the monsoon to India, Persia and Majapahit.", "trade"),
  ("h3", [BLUE, BLACK, GREEN], "flame", GOLD),
  "Swahili civilization grew here as it did in ours, but its traders and settlers came from Zoroastrian Persia and Hindu India. The Shirazi dynasty of Kilwa claims descent from a Persian prince, keeps a fire temple beside its cathedral of coral stone, and rules the coast from Mombasa to the Rufiji.",
  party=("Waungwana", "Council of Gentlemen")),
C("MLW", "MRV", "Maravi Empire", "Maravi", "neutrality", "despotism", "Kalonga Masula III", 770,
  [770],
  ("Lake of Stars", "The Maravi command the trade of the great lake.", "people"),
  ("h3", [BLACK, RED, GREEN], "sun", RED),
  "The Maravi confederacy of the lakeshore grew into a solid kingdom under the Kalonga, who rules from the shores of Lake Nyasa.",
  party=("Kalonga", "Royal Council")),
C("BAR", "LOZ", "Lozi Kingdom", "Lozi", "neutrality", "oligarchism", "Litunga Mulambwa IV", 981,
  [771, 981],
  ("Kuomboka", "Every flood season the Litunga's royal barge leads the nation to higher ground.", "unity"),
  ("v2", [RED, BLACK], "star", WHITE),
  "The Lozi kingdom of the upper Zambezi floodplains, under the Litunga, now rules from Barotseland to the copper hills of the north.",
  party=("Kuta", "Council of the Kuta")),
C("ZIM", "MUT", "Mutapa Empire", "Shona", "neutrality", "despotism", "Mwenemutapa Nyatsimba XVII", 545,
  [545, 896, 897, 891, 544],
  ("Walls of Great Zimbabwe", "The stone city is still the capital of a great southern empire.", "defense"),
  ("h3", [GREEN, YELLOW, RED], "diamond", GOLD),
  "Great Zimbabwe was never abandoned. Its successor, the Mutapa Empire, controls the gold fields and the Zambezi trade from the stone walls of its capital to the Indian Ocean port of Sofala.",
  party=("Dare", "Council of the Dare")),
C("BOT", "NGW", "Ngwato Kingdom", "Tswana", "neutrality", "moderatism", "Kgosi Sekgoma IV", 542,
  [542],
  ("Kgotla", "The Tswana kgotla lets every man speak before the chief decides.", "unity"),
  ("h3", [SKY, BLACK, SKY], None, None),
  "The Tswana chiefdoms of the Kalahari fringe, led by the Ngwato, keep their kgotla assemblies and their cattle.",
  party=("Kgotla", "Great Kgotla")),
C("NMB", "ZUL", "Zulu Kingdom", "Zulu", "neutrality", "despotism", "King Cetshwayo III", 719,
  [719, 275],
  ("Impi", "The regimental system of Shaka still makes every Zulu man a soldier.", "martial"),
  ("h3", [BLACK, WHITE, GREEN], "diamond", GOLD),
  "Shaka built his kingdom in the 1820s, and in this world it was never broken by colonial war. The Zulu now rule from Natal to the gold of the Transvaal. Their impis carry rifles from Hanseatic factories, and their regiments are the best-drilled army in Africa.",
  party=("Ibandla", "Royal Ibandla")),
C("SAF", "CAP", "Dominion of the Cape", "Cape", "democratic", "conservatism", "Governor-Jarl Pieter Haraldsen", 681,
  [681, 541, 893, 894, 895],
  ("Tavern of the Seas", "Every ship rounding Africa stops at the Cape.", "naval"),
  ("canton", [NAVY, CRIMSON], "star", GOLD),
  "The North Sea Empire's sailors took the Cape in 1652 as a waystation to the east. The colony grew into a self-governing dominion of Anglo-Danish settlers, Khoikhoi and Malagasy. It hugs the coast, and it has made a nervous peace with the Zulu across the mountains.",
  party=("Volksraad", "Cape Volksraad"), overlord="ENG", faction="north"),
C("MAD", "MER", "Merina Kingdom", "Malagasy", "neutrality", "oligarchism", "Queen Ranavalona IV", 543,
  [543, 708, 706, 707, 709],
  ("Highland Monarchy", "The Merina queens have unified the great island and its neighbours.", "unity"),
  ("v2", [WHITE, RED], "ring", GREEN),
  "No Frankish expedition ever conquered Madagascar. The Merina queens of Antananarivo unified the island in the 1800s and now rule the Mascarenes and the Comoros as well. Their realm sits on the shipping lanes between Africa and India.",
  party=("Andriana", "Council of the Andriana")),

# ======================================================================
# SOUTH ASIA
# ======================================================================
C("AFG", "SHA", "Shahi Kingdom of Kabul", "Shahi", "neutrality", "despotism", "Shahi Jayapala IX", 267,
  [267, 1005, 1006, 1008, 442, 987, 443, 989],
  ("Gatekeepers of India", "The Shahis hold the Khyber, the door to the subcontinent.", "defense"),
  ("h2", [SAFFRON, NAVY], "sun", WHITE),
  "The Hindu Shahis of Kabul were destroyed by the Ghaznavids in our world. Here they still rule the Hindu Kush and Gandhara from Kabul, a Hindu-Buddhist kingdom guarding the passes of India against Persians, Sogdians and Mongols. The Bamiyan Buddhas still stand.",
  party=("Sabha", "Royal Sabha")),
C("RAJ", "KNJ", "Empire of Kanauj", "Kanaujian", "neutrality", "oligarchism", "Maharajadhiraja Mihira Bhoja VI", 438,
  [438, 439, 440, 986, 435, 436],
  ("Heart of Aryavarta", "Kanauj sits on the Gangetic plain, the richest farmland on earth.", "people"),
  ("h3", [SAFFRON, WHITE, GREEN], "wheel", NAVY),
  "The Gurjara-Pratihara empire of Kanauj stopped the Arab armies in our eighth century. In this world there were no Arab armies, and it simply kept growing. Kanauj is the greatest of India's empires, ruling the Gangetic heartland under an emperor and an assembly of princes. It is huge and populous, and it is uneasily modernizing.",
  party=("Rajasabha", "Imperial Rajasabha")),
C("RJP", "RJT", "Rajput Confederacy", "Rajput", "neutrality", "despotism", "Maharana Hammir Sisodia", 433,
  [433, 428, 991, 437],
  ("Code of the Kshatriya", "Rajput warriors would rather die than retreat.", "martial"),
  ("h2", [SAFFRON, CRIMSON], "sun", GOLD),
  "With no sultans to fight, the Rajput clans fought each other until 1720. Then the Maharana of Mewar forged them into a confederacy of desert fortresses and Gujarati ports.",
  party=("Rajmandal", "Council of Rajas")),
C("BAN", "PAL", "Pala Empire of Gauda", "Bengali", "democratic", "socialism", "Mahasammata Dharmapala XI", 431,
  [430, 431, 432, 434, 990, 426],
  ("Nalanda Reborn", "Nalanda, the greatest university of the ancient world, was never burned.", "scholar"),
  ("v2", [GREEN, SAFFRON], "wheel", WHITE),
  "The first Pala king was elected by his people in 750, and the Buddhist Pala empire of Bengal kept the tradition. Nalanda and Vikramashila were never sacked. Bengal is the Buddhist heart of India and a fertile, crowded, argumentative democracy. Its universities export philosophers to all of Asia.",
  party=("Sangha", "People's Sangha")),
C("MYS", "VJN", "Vijayanagara Empire", "Vijayanagaran", "neutrality", "despotism", "Raya Krishnadeva IV", 425,
  [423, 424, 425, 427, 982, 983, 984, 733, 320, 321, 429],
  ("City of Victory", "Hampi remains the most magnificent city in India.", "trade"),
  ("v3", [RED, YELLOW, RED], "sun", RED),
  "No Deccan sultanates destroyed Vijayanagara at Talikota in 1565. The 'City of Victory' at Hampi became the capital of a South Indian empire that rules from Bombay to Cape Comorin, trades with Kilwa and Majapahit, and builds temples taller than Roman cathedrals.",
  party=("Nayaka", "Council of Nayakas")),
C("KAS", "KSM", "Karkota Kingdom of Kashmir", "Kashmiri", "neutrality", "moderatism", "King Lalitaditya IX", 441,
  [441, 787],
  ("Valley of Scholars", "Kashmir's Shaiva philosophers are revered from Tibet to Kanauj.", "scholar"),
  ("h2", [WHITE, RED], "sun", GOLD),
  "The Karkota dynasty of Lalitaditya made Kashmir an empire in the eighth century. It shrank back to its valley but has endured there for twelve centuries as a mountain kingdom of temples and scholars.",
  party=("Parishad", "Royal Parishad")),
C("SRL", "LKA", "Kingdom of Lanka", "Sinhalese", "neutrality", "moderatism", "King Parakramabahu XI", 422,
  [422, 281],
  ("Island of Dhamma", "Lanka is the guardian of the Buddha's tooth and Theravada orthodoxy.", "faith"),
  ("v2", [ORANGE, CRIMSON], "wheel", GOLD),
  "No Portuguese, Dutch or British ever landed in this Lanka. Its kings at Anuradhapura and Kandy rule the island and the Maldives as a Theravada Buddhist monarchy, with tanks, temples and a small, efficient navy.",
  party=("Sangha", "Royal Council")),
C("NEP", "NPL", "Licchavi Kingdom of Nepal", "Nepali", "neutrality", "despotism", "King Amshuverma IV", 323,
  [323, 985],
  ("Gurkha Regiments", "Nepal's soldiers are famous across Asia.", "martial"),
  ("tri", [CRIMSON, BLUE, CRIMSON], "sun", WHITE),
  "The Licchavi dynasty of Kathmandu still rules the Himalayan valleys and the passes to Tibet. Its mountain regiments hire themselves out to half the monarchs of Asia.",
  party=("Bharadar", "Bharadar Sabha")),
C("BHU", "DRK", "Druk Gyalkhap", "Bhutanese", "neutrality", "despotism", "Druk Desi Jigme Namgyal II", 324,
  [324],
  ("Thunder Dragon", "The Druk kingdom is protected by its mountains and its monks.", "faith"),
  ("bend", [YELLOW, ORANGE], "diamond", WHITE),
  "The Land of the Thunder Dragon is a Buddhist theocracy in the eastern Himalaya, much as it is in our own world.",
  party=("Tshogdu", "Assembly")),
C("TIB", "TBT", "Tibetan Empire", "Tibetan", "neutrality", "despotism", "Tsenpo Trisong Detsen IV", 322,
  [322, 601, 757, 758, 752, 604, 754, 755, 753],
  ("Roof of the World", "The Tibetan plateau is a fortress that no army has ever crossed in force.", "defense"),
  ("v2", [BLUE, RED], "sun", YELLOW),
  "The Tibetan Empire of the Yarlung kings never fragmented in the ninth century. It still rules the plateau and Amdo under a Tsenpo who is half emperor and half bodhisattva.",
  party=("Kashag", "Imperial Kashag")),

# ======================================================================
# EAST ASIA
# ======================================================================
C("CHI", "SON", "Empire of the Great Song", "Song", "democratic", "conservatism", "Chancellor Zhao Wenyuan", 596,
  but(own("CHI"), 752, 751) + [615, 609],
  ("Examination Bureaucracy", "Song China still selects its officials by examination, now with modern subjects.", "scholar"),
  ("v3", [RED, YELLOW, RED], "sun", RED),
  "The Mongols conquered the Song in our world. Here the Southern Song held the Yangzi long enough for the Mongols to turn west, and a Song restoration in 1368 reclaimed the north. Song China industrialized in the 1800s under a constitutional emperor and a scholar-parliament chosen by examination. It is the richest country in Asia and the most divided: warlords, Mohists and secessionist kingdoms nibble at its edges.",
  party=("Hanlin", "Hanlin Academy Party")),
C("PRC", "MOH", "Mohist Commune of Yan'an", "Mohist", "communism", "anti_revisionism", "Grand Master Qin Xiuli", 1032,
  [622, 1032, 1046],
  ("Universal Love", "The Mohist doctrine of jian ai (impartial care) has become a revolutionary creed.", "revolution"),
  ("plain", [CRIMSON], "ring", YELLOW),
  "Chinese radicals did not need Marx. They rediscovered Mozi, the ancient philosopher of universal love, of austerity and of defensive war. In 1927 the Mohist uprising was driven out of the cities into the loess hills of Shaanbei. The Mohist Commune of Yan'an is ascetic, disciplined and egalitarian, and it is in close contact with comrades in Constantinople.",
  party=("Mojia", "Mohist Fraternity")),
C("GXC", "NYU", "Kingdom of Nanyue", "Yue", "neutrality", "oligarchism", "King Zhao Tuo XXVI", 592,
  [591, 592, 593, 594, 599, 1033, 326, 729, 728],
  ("Canton Trade", "Guangzhou is the busiest port in the world.", "trade"),
  ("h2", [RED, BLACK], "star", YELLOW),
  "The ancient kingdom of Nanyue, conquered by the Han and revived in the chaos of the 1900s, rules the Cantonese south from Guangzhou. It is a merchant monarchy that controls the trade of the South China Sea.",
  party=("Yue", "Merchants' Council")),
C("YUN", "DAL", "Kingdom of Dali", "Dali", "neutrality", "moderatism", "King Duan Zhengxing VII", 747,
  [325, 747, 751],
  ("Buddhist Kingdom of the Southwest", "Dali's kings abdicate to become monks.", "faith"),
  ("v2", [WHITE, BLUE], "wheel", GOLD),
  "The Buddhist kingdom of Dali was destroyed by Kublai Khan in our world. Here it survived the Mongols as a vassal and outlasted them. It is a tranquil, mountainous kingdom whose rulers traditionally end their reigns as monks.",
  party=("Sangha", "Royal Sangha")),
C("XSM", "XIA", "Great Xia", "Tangut", "neutrality", "despotism", "Emperor Li Yuanhao XII", 616,
  [283, 616, 756, 1040, 1044, 1045, 746],
  ("Tangut Script", "The Western Xia guard their unique script and their unique cavalry.", "steppe"),
  ("h2", [WHITE, BLACK], "diamond", RED),
  "The Tangut empire of the Western Xia was annihilated by Genghis Khan in 1227. Here Genghis died at the siege, the Tanguts were spared, and the Great Xia still rules the Gansu corridor and the Ordos as a Buddhist steppe state.",
  party=("Mingsha", "Imperial Council")),
C("MON", "MGL", "Great Mongol Ulus", "Mongol", "neutrality", "despotism", "Khagan Temür Bayan", 330,
  [330, 817, 818, 819, 820, 611, 612, 1043, 621, 329, 564, 563, 761],
  ("Heirs of the Golden Lineage", "Every Mongol rider is a descendant of the conquerors of the world.", "steppe"),
  ("v3", [RED, BLUE, RED], "sun", GOLD),
  "The Mongols conquered half the world and lost it again. The Great Ulus kept the heartland: the steppe from Inner Mongolia to Lake Baikal, ruled by a Buddhist Khagan of the Golden Lineage. It is a weak giant with a proud memory. Its neighbours are not sure whether it is a threat or an opportunity.",
  party=("Khural", "Great Khural")),
C("SIK", "UYG", "Uyghur Khaganate", "Uyghur", "communism", "marxism", "Teacher Bögü Arslan", 760,
  own("SIK") + [586],
  ("Religion of Light", "Manichaean dualism and Marxist dialectic have merged into a single creed.", "revolution"),
  ("h2", [WHITE, TURQ], "sun", WHITE),
  "The Uyghur Khaganate made Manichaeism its state religion in 762, a faith of Light against Darkness. Its oasis cities of the Tarim survived Mongols and Song alike. In 1925 young Manichaean radicals recognized Marx as the latest messenger of Light and overthrew the Khagan. The Uyghur Khaganate is now a revolutionary Manichaean commune. It is unlike anything else on earth, and it is allied in spirit with Rome.",
  party=("Electi", "Council of the Elect")),
C("MAN", "JIN", "Jin Empire of the Jurchens", "Jurchen", "fascism", "fascism_ideology", "Emperor Wanyan Aguda IX", 714,
  [328, 610, 714, 715, 716, 717, 745, 561, 409, 408, 560, 655, 657],
  ("Meng'an Mouke", "Jurchen military households are organized for total war.", "martial"),
  ("v2", [BLACK, GOLD], "sun", WHITE),
  "The Jurchen Jin dynasty conquered northern China once, in 1127. Its heirs never forgot. Revived in Manchuria and the Amur, the Jin Empire is now a militarist state that dreams of crossing the Great Wall again and sees Song China as its rightful prey.",
  party=("Meng'an", "Banner Council")),
C("KOR", "GRY", "Kingdom of Goryeo", "Korean", "neutrality", "moderatism", "King Wang Geon XXXIV", 525,
  [525, 527, 1028, 1029, 1030, 1031],
  ("Turtle Ships and Movable Type", "Goryeo printed books with metal type two centuries before anyone else.", "scholar"),
  ("cross", [WHITE, RED], "disc", BLUE),
  "The Goryeo dynasty of Wang Geon never fell to a Joseon coup and never to Japan. Korea is an old, learned Buddhist kingdom that has modernized cautiously, and it watches the Jin and the Yamato with equal alarm.",
  party=("Dopyeong", "State Council")),
C("JAP", "YMT", "Yamato Shogunate", "Yamato", "fascism", "fascism_ideology", "Shogun Taira no Kiyonori", 531,
  [282, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 555, 1018, 1019, 1020, 526, 524, 633, 645, 646, 647, 648, 684, 638],
  ("Way of the Warrior", "The samurai caste was never abolished; it became the officer corps.", "martial"),
  ("plain", [WHITE], "disc", CRIMSON),
  "The Taira won the Genpei War in this world, and the warrior shogunate they founded never gave power back to the Emperor in Kyoto. Modernized by force after Frisian ships arrived in 1850, the Yamato Shogunate is an aggressive military state. It already holds Taiwan and the Pacific islands and wants an empire on the mainland.",
  party=("Bakufu", "Bakufu Council")),

# ======================================================================
# SOUTHEAST ASIA AND OCEANIA
# ======================================================================
C("BRM", "BGN", "Kingdom of Bagan", "Burmese", "neutrality", "despotism", "King Anawrahta X", 640,
  own("BRM"),
  ("Ten Thousand Temples", "Bagan's temple plain is the spiritual heart of Theravada Asia.", "faith"),
  ("h3", [YELLOW, GREEN, RED], "star", WHITE),
  "Bagan was sacked by the Mongols in 1287 in our world. Here King Narathihapate held and his descendants still rule the Irrawaddy from the city of ten thousand temples. Bagan is a devout Theravada monarchy and the rice-bowl of Southeast Asia.",
  party=("Hluttaw", "Royal Hluttaw")),
C("SIA", "AYU", "Kingdom of Ayutthaya", "Siamese", "neutrality", "moderatism", "King Ramathibodi IX", 289,
  [289, 869, 724],
  ("River Capital", "Ayutthaya's canals make it the Venice of the East.", "trade"),
  ("stripes", [RED, WHITE], "wheel", BLUE),
  "Ayutthaya was never sacked by Burma in 1767, because Bagan was busy elsewhere. The Siamese kingdom grew into a cosmopolitan trading state of canals and palaces.",
  party=("Senabodi", "Council of Ministers")),
C("CAM", "KHM", "Khmer Empire", "Khmer", "neutrality", "despotism", "Emperor Jayavarman XIV", 741,
  [741, 868],
  ("Angkor's Waterworks", "The barays of Angkor still irrigate the richest rice lands of the Mekong.", "people"),
  ("h3", [BLUE, RED, BLUE], "diamond", WHITE),
  "Angkor was never abandoned. The Khmer god-kings maintained their great reservoirs, adapted to the drought of the fourteenth century, and still rule the lower Mekong from the city of temples.",
  party=("Devaraja", "Cult of the God-King")),
C("LAO", "LXG", "Kingdom of Lan Xang", "Lao", "neutrality", "moderatism", "King Fa Ngum VIII", 670,
  [670],
  ("A Million Elephants", "Lan Xang's war elephants are still kept for ceremony and for logging.", "defense"),
  ("h3", [RED, BLUE, RED], "ring", WHITE),
  "The 'Kingdom of a Million Elephants' has held the middle Mekong since 1353 and has never been divided.",
  party=("Sena", "Royal Council")),
C("VIN", "DVT", "Dai Viet", "Vietnamese", "neutrality", "oligarchism", "Emperor Lê Thánh Minh", 671,
  [671],
  ("Southern Advance Halted", "Dai Viet turned inward after Champa stopped its southern march.", "people"),
  ("plain", [YELLOW], "star", RED),
  "The Vietnamese of the Red River delta drove out the Song and the Mongols but never conquered Champa. Dai Viet is a dense, Confucian, highly militarized state in the north.",
  party=("Trieu Dinh", "Imperial Court")),
C("SUR", "CHM", "Kingdom of Champa", "Cham", "neutrality", "moderatism", "Po Rome V", 286,
  [286, 1017],
  ("Sea Kingdom of the Cham", "Cham sailors and pirates know every reef of the South China Sea.", "naval"),
  ("h2", [RED, YELLOW], "sun", YELLOW),
  "The Hindu kingdom of Champa, with no Islam to convert it and no Vietnamese conquest to end it, still rules the central coast of Indochina, defended by its fleet and its brick towers.",
  party=("Hamu", "Royal Council")),
C("MAL", "SRV", "Srivijaya Thalassocracy", "Srivijayan", "neutrality", "oligarchism", "Maharaja Balaputradewa XIX", 672,
  [336, 1021, 672],
  ("Lord of the Straits", "Srivijaya taxes every ship that passes through the Straits of Malacca.", "naval"),
  ("h2", [RED, GOLD], "wheel", RED),
  "Srivijaya ruled the Straits of Malacca for six hundred years in our world, and in this one it still does. Its Buddhist maharajas grow rich on every ship that sails between India and China.",
  party=("Datu", "Council of Datus")),
C("INS", "MJP", "Majapahit Empire", "Majapahit", "neutrality", "despotism", "Maharaja Hayam Wuruk VII", 335,
  [335, 334, 1022, 667, 668, 669, 673, 738, 721, 333, 1023, 1024, 711, 712, 520, 870],
  ("Nusantara", "Gajah Mada's oath to unite the archipelago has been fulfilled.", "naval"),
  ("h2", [RED, WHITE], "sun", GOLD),
  "The Hindu-Buddhist empire of Majapahit never fell to the Islamic sultanates of the coast, because there were none. Gajah Mada's oath to unite Nusantara was fulfilled. Majapahit rules from Java to Borneo to the spice islands, and its Makassan traders settled the north coast of Marege', the land we call Australia.",
  party=("Bhattara", "Council of the Bhattara")),
C("PHI", "TND", "Kingdom of Tondo", "Tagalog", "neutrality", "moderatism", "Lakan Dula IX", 327,
  own("PHI"),
  ("Barangay Federation", "Tondo is a federation of island chiefdoms under the Lakan.", "naval"),
  ("h3", [BLUE, WHITE, RED], "sun", GOLD),
  "No Gothic or Spanish galleon ever claimed the islands. The Lakan of Tondo united the barangays of Luzon, the Visayas and Mindanao into a Hindu-Buddhist maritime kingdom that trades with Song, Majapahit and Fusang.",
  party=("Maginoo", "Council of Maginoo")),
C("AST", "NYL", "Dominion of Nýjaland", "Nýjalander", "democratic", "liberalism", "Governor-General Edward Haraldsson", 285,
  [285, 517, 518, 519, 521, 872, 873, 674, 522, 871, 523, 979, 737, 634],
  ("Southern Frontier", "Nýjaland's settlers are tough, egalitarian and far from home.", "people"),
  ("canton", [NAVY, CRIMSON], "star", WHITE),
  "Anglo-Danish whalers found the great southern land in 1770 and called it Nýjaland, the New Land. Settler colonies spread down the eastern coast. They still dispute the northern shore with Majapahit's Makassan towns of Marege'. Nýjaland is a self-governing dominion of the North Sea Empire, and it is restless.",
  party=("Althing", "Nýjaland Althing"), overlord="ENG", faction="north"),
C("NZL", "AOT", "Kingdom of Aotearoa", "Māori", "neutrality", "moderatism", "Kīngi Pōtatau IV", 284,
  [284, 723],
  ("Kīngitanga", "The Māori King movement united the iwi long before the settlers came.", "jungle"),
  ("h2", [BLACK, RED], "ring", WHITE),
  "The Kīngitanga movement united the Māori iwi under a single king before European settlers arrived in strength. Aotearoa is an independent Polynesian kingdom. It has a modern army, it trades with Nýjaland, and it keeps a firm 'no' on the subject of land sales.",
  party=("Kauhanganui", "Great Council")),
C("FIJ", "TGA", "Tu'i Tonga Empire", "Tongan", "neutrality", "despotism", "Tu'i Tonga Laufilitonga II", 636,
  [726, 636, 641, 635, 734, 639, 643, 725, 642, 727, 270],
  ("Ocean Voyagers", "Tongan navigators cross thousands of miles by stars and swells.", "naval"),
  ("cross", [WHITE, RED], "disc", RED),
  "The maritime chiefdom of the Tu'i Tonga, which in the 1200s held sway over Samoa, Fiji and beyond, revived in the 1800s with modern ships. It now unites much of Polynesia and Melanesia in a vast ocean empire of scattered islands.",
  party=("Fale Alea", "House of Nobles")),
C("HAW", "HWI", "Kingdom of Hawai'i", "Hawaiian", "neutrality", "moderatism", "Queen Ka'iulani II", 629,
  [629, 630, 631, 632],
  ("Crossroads of the Pacific", "Every ship between Fusang and Asia stops in Honolulu.", "naval"),
  ("stripes", [WHITE, RED], "canton_cross", NAVY),
  "Kamehameha united the islands in 1810 as he did in our world, but no Vinlander planters overthrew his heirs. Hawai'i is an independent constitutional kingdom and the crossroads of the Pacific.",
  party=("Ahahui", "Royal Council")),
C("RAP", "RPN", "Rapa Nui", "Rapanui", "neutrality", "moderatism", "Ariki Mau Hotu Matu'a IV", 948,
  [948],
  ("The Moai", "The great stone faces still watch over their people.", "faith"),
  ("plain", [WHITE], "ring", RED),
  "The most remote inhabited island on earth was never ravaged by slavers. Rapa Nui is a tiny kingdom, and its moai still stand upright.",
  party=("Tangata", "Council of Elders")),

# ======================================================================
# THE AMERICAS
# ======================================================================
C("CAN", "MRK", "Dominion of Markland", "Marklander", "democratic", "conservatism", "Jarl-Governor Leif Moore", 468,
  own("CAN") + [331, 332, 730],
  ("Timber and Furs", "Markland's forests built the North Sea fleet.", "industry"),
  ("canton", [NAVY, GREEN], "star", WHITE),
  "Leif Erikson named the forested coast Markland, 'Land of Forest', in the year 1000. The Norse never left. The settlement grew into a North Sea Empire dominion stretching from Labrador to the Pacific, built on timber, furs and fish. Its relations with the Haudenosaunee and the Cree are older than the Vinland Commonwealth.",
  party=("Thing", "Markland Thing"), overlord="ENG", faction="north"),
C("USA", "VIN", "Commonwealth of Vinland", "Vinlander", "democratic", "liberalism", "Lawspeaker Ingrid Halvorsen", 357,
  [357, 358, 359, 360, 361, 362, 816, 363, 364, 261, 393, 394, 395, 396, 391, 392, 369, 368, 373],
  ("The Althing of the West", "Vinland's democracy descends from the Norse Thing and the Haudenosaunee Great Law.", "industry"),
  ("canton", [WHITE, BLUE], "star", WHITE),
  "Norse settlers from Greenland survived in Vinland by trading and intermarrying with the Mi'kmaq and the Haudenosaunee instead of fighting them. Over eight centuries the settlements grew into a commonwealth from the Atlantic to the Great Lakes. Its constitution of 1779 borrowed equally from the Althing and the Great Law of Peace. Vinland is industrial, democratic and isolationist. It has no Pacific coast, no Gulf coast, and Gothic, Lakota and Fusang neighbours it does not entirely trust.",
  party=("Althing", "Party of the Althing")),
C("CSA", "NGO", "Viceroyalty of New Gothia", "New Gothic", "neutrality", "oligarchism", "Viceroy Wamba Alarico", 371,
  [365, 366, 367, 370, 371, 372, 375, 686, 690, 693],
  ("Plantation Aristocracy", "New Gothia's Gothic grandees rule vast estates along the Gulf.", "trade"),
  ("h3", [CRIMSON, GOLD, CRIMSON], "star", CRIMSON),
  "Gothic caravels reached the Caribbean in 1492. Unable to break the great native empires, the Goths built a colonial viceroyalty around the Gulf of Mexico instead, from Florida to Texas, ruled from New Orleans. It is a hierarchical, Catholic and loyal satellite of Toledo.",
  party=("Audiencia", "Royal Audiencia"), overlord="SPR"),
C("ITZ", "OSK", "Očhéthi Šakówiŋ Confederacy", "Lakota", "neutrality", "moderatism", "Itancan Tatanka Najin", 390,
  [389, 390, 384, 383, 374, 388, 381, 382],
  ("Horse Nations", "The Plains nations are the finest light cavalry and mounted riflemen in the world.", "steppe"),
  ("h3", [BLUE, WHITE, RED], "ring", BLACK),
  "Horses spread north from Gothic ranches in the 1600s. The Seven Council Fires of the Lakota, Dakota and Nakota built a confederacy across the Great Plains that no settler state could break. It is a land of horses, rail-towns and buffalo herds. Its council meets each summer in the Black Hills.",
  party=("Oceti", "Seven Council Fires")),
C("USB", "FUS", "Republic of Fusang", "Fusang", "democratic", "liberalism", "President Lin Haiyun", 378,
  [378, 385, 386, 379, 387, 380],
  ("Gold Mountain", "Fusang's ports and gold fields made it the Pacific's richest republic.", "trade"),
  ("h3", [RED, YELLOW, BLUE], "sun", WHITE),
  "Chinese chronicles told of Fusang, a land far to the east. In 1601 a Song treasure fleet blown off course found it. Chinese settlers, later joined by Japanese, Korean and Polynesian migrants, built a Pacific republic from San Francisco to Puget Sound. Fusang broke from Song China in 1848 and is a booming, polyglot democracy facing Asia.",
  party=("Gonghe", "Republican Assembly")),
C("MEX", "MXA", "Mexica Empire of Anahuac", "Mexica", "fascism", "fascism_ideology", "Huey Tlatoani Cuauhtémoc IV", 277,
  [277, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 376, 377],
  ("Flower Wars", "The Mexica cult of the warrior has been turned into a modern militarism.", "martial"),
  ("v3", [GREEN, WHITE, RED], "sun", GOLD),
  "In this world the Goths came as traders and the Mexica got steel, horses and gunpowder before they got smallpox. The Triple Alliance survived, modernized and expanded north. The Huey Tlatoani now rules an industrial empire from Tenochtitlan, and an ultranationalist cult of the Fifth Sun preaches that the empire must expand or die.",
  party=("Tlatocan", "Movement of the Fifth Sun")),
C("GUA", "MAY", "Maya League of Mayapan", "Maya", "neutrality", "moderatism", "Halach Uinic K'inich Yax", 474,
  [313, 314, 312, 311, 474, 475],
  ("Calendar Keepers", "Maya astronomers maintain the most accurate calendar on earth.", "scholar"),
  ("h3", [BLUE, WHITE, BLUE], "sun", GREEN),
  "The Maya city-states, never conquered by Spaniards, re-formed the League of Mayapan in the 1700s. The League rules Yucatán and the highlands of Guatemala as a confederation of cities under an elected Halach Uinic.",
  party=("Multepal", "Joint Government")),
C("NIC", "IST", "Isthmian Confederation", "Isthmian", "democratic", "socialism", "Speaker Ana Lucía Urracá", 317,
  [317, 316, 304, 685],
  ("The Canal", "The Isthmian canal was dug by the Confederation and is owned by it.", "trade"),
  ("h3", [BLUE, WHITE, BLUE], "star", RED),
  "The Chibcha-speaking peoples of the isthmus formed a confederation in 1821 and, with Hanseatic capital and their own labour, cut the canal between the oceans in 1914. They own it, they tax it, and they are very nervous about the Mexica.",
  party=("Concejo", "Isthmian Concejo")),
C("CUB", "TAI", "Taíno Cacicazgo", "Taíno", "neutrality", "moderatism", "Cacique Hatuey III", 315,
  [315, 689],
  ("Sons of Hatuey", "The Taíno revolt of 1512 drove the Goths into the sea.", "jungle"),
  ("tri", [RED, BLUE, WHITE], "sun", GOLD),
  "In our world the cacique Hatuey was burned by Spaniards. Here he won. His revolt drove the Gothic colonists from Cuba, and the Taíno chiefdoms of Cuba and Jamaica became a sovereign cacicazgo of sugar, tobacco and fierce independence.",
  party=("Batey", "Council of Caciques")),
C("DOM", "KSK", "Republic of Kiskeya", "Kiskeyan", "democratic", "socialism", "President Anacaona Guarionex", 319,
  [318, 319],
  ("One Island", "Kiskeya was never divided into two colonies.", "people"),
  ("cross", [BLUE, RED], "star", WHITE),
  "The island the Taíno called Kiskeya ('Mother of All Lands') freed itself from Gothic rule in 1804 as a single republic of Taíno, African and Gothic peoples. It is a radical, democratic and multiracial state.",
  party=("Areyto", "People's Areyto")),
C("TRI", "KLN", "Kalinago Confederacy", "Kalinago", "neutrality", "moderatism", "Ubutu Tegremond II", 691,
  [691, 692, 308],
  ("Island Raiders", "Kalinago war-canoes once terrorized every colonist in the Antilles.", "naval"),
  ("h3", [GREEN, YELLOW, BLACK], "star", WHITE),
  "The fierce Kalinago of the Lesser Antilles never submitted to anyone. Their island confederacy now has a small modern navy and a large reputation.",
  party=("Carbet", "Council of the Carbet")),
C("COL", "MUI", "Muisca Confederation", "Muisca", "neutrality", "oligarchism", "Zipa Tisquesusa VIII", 306,
  [306, 486, 493],
  ("El Dorado", "The Muisca gold ceremony at Lake Guatavita gave birth to a legend.", "trade"),
  ("h3", [YELLOW, GREEN, RED], "sun", YELLOW),
  "The Muisca of the Bogotá highlands, the people of the El Dorado legend, joined their zipa and zaque realms into one confederation in the 1500s. They keep their gold and their highlands and trade emeralds with the world.",
  party=("Zipazgo", "Council of the Zipa")),
C("VEN", "KLV", "Klein-Venedig", "Klein-Venedig", "democratic", "conservatism", "Statthalter Ambrosius Ehinger IX", 307,
  [307, 488, 489, 687],
  ("Hanseatic Plantations", "Lübeck capital runs the cocoa and oil of Klein-Venedig.", "trade"),
  ("h2", [WHITE, RED], "ring", RED),
  "In 1528 the Welser banking house leased the Venezuelan coast in our world and failed within a generation. Here the Hanse leased it and did not fail. Klein-Venedig, 'Little Venice', is a Hanseatic colony of plantations and, recently, oil derricks around Lake Maracaibo.",
  party=("Kontor", "Party of the Kontor"), overlord="GER"),
C("PRU", "TWS", "Tawantinsuyu", "Inca", "neutrality", "despotism", "Sapa Inca Túpac Yupanqui XI", 492,
  own("PRU", "ECU", "BOL") + [951, 952, 506, 279, 508, 960, 959],
  ("Mit'a Labour System", "The Inca labour tax builds roads, terraces and factories.", "people"),
  ("h3", [RED, YELLOW, RED], "sun", YELLOW),
  "The Inca civil war of Huáscar and Atahualpa ended in 1532 without any foreign invaders to exploit it. Tawantinsuyu, the 'Realm of the Four Quarters', survived to adopt Gothic steel and Hanseatic engines. It is a vast, highly organized Andean empire from Quito to Santiago, held together by the old roads, the mit'a labour tax and the divine Sapa Inca.",
  party=("Inka", "Imperial Council of the Four Quarters")),
C("CHL", "MPC", "Mapuche Wallmapu", "Mapuche", "neutrality", "moderatism", "Toqui Lautaro Kalfükura", 950,
  [950, 949, 507, 512, 955, 954, 953, 958, 511],
  ("Never Conquered", "The Mapuche resisted the Inca and the Goths alike.", "defense"),
  ("h3", [BLUE, GREEN, RED], "star", WHITE),
  "The Mapuche stopped the Inca at the Maule river and later stopped the Goths. Their land, Wallmapu, stretches across the Andes from the Pacific to the pampas and down to Tierra del Fuego. A war-leader, the toqui, is chosen by the lonkos in time of danger.",
  party=("Koyagtun", "Great Parliament")),
C("ARG", "LPT", "Gothic Republic of La Plata", "Platine", "democratic", "conservatism", "Consul Teodorico Sisebuto", 278,
  [278, 956, 957, 509, 300, 945, 946, 299],
  ("Beef and Grain", "The pampas feed half the world.", "trade"),
  ("h3", [SKY, WHITE, SKY], "sun", GOLD),
  "Gothic settlers on the Río de la Plata broke from Toledo in 1816 and founded a republic of ranchers and port merchants. La Plata sends its beef and grain all over the world and argues constantly with its Mapuche, Inca and Guaraní neighbours.",
  party=("Cabildo", "Cabildo Party")),
C("PAR", "GUR", "Guaraní Commonwealth", "Guaraní", "communism", "anarchist_communism", "Mburuvicha Sepé Tiaraju II", 301,
  [301, 688, 504, 510, 944],
  ("Tekoha", "Land belongs to the community, as the Guaraní have always held.", "revolution"),
  ("h3", [RED, WHITE, BLUE], "star", YELLOW),
  "The Guaraní always held their land in common. In 1756 Sepé Tiaraju led a rising that drove out Gothic and Irish settlers alike. The Guaraní Commonwealth has been communal for two centuries and avowedly communist since 1921. It is a small, determined state between larger neighbours.",
  party=("Aty Guasu", "Great Assembly")),
C("BRA", "HYB", "Republic of Hy-Brasil", "Hy-Brasilian", "democratic", "liberalism", "Taoiseach Brendan Ó Dálaigh-Tupinambá", 500,
  but(own("BRA"), 504, 944),
  ("Isle of the Blessed", "Hy-Brasil's founders believed they had found paradise, and they built accordingly.", "people"),
  ("h2", [GREEN, GOLD], "ring", GREEN),
  "Gaelic monks had long told of Hy-Brasil, a blessed isle in the western ocean. In 1512 Irish sailors went looking for it and found a continent. The colony mixed with the Tupi and Tupinambá, freed itself from the High King in 1822, and is now an enormous Gaelic-Tupi republic of coffee, rubber and rapid growth.",
  party=("Dáil", "Dáil of Hy-Brasil")),
]

# Factions created at game start
FACTIONS = {
    "red":   ("TUR", "rpr_faction_red_ecumene"),
    "fire":  ("PER", "sao_faction_sacred_fire"),
    "north": ("ENG", "aw_faction_north_sea_thing"),
}
